✨ feat: add session group manager
lobehub/lobehub pull request #1055
Opened 2024-01-15 14:31 UTC by canisminor1990

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

在 https://github.com/lobehub/lobe-chat/pull/1045 的基础上：

- 增加分组重命名 / 删除 / 管理
- 在管理中支持对分组进行排序
- 当导入的助手分组不存在时，自动移动到默认列表
- 其他项: 修改一些样式细节

@arvinxx @Justin3go 

#### 📝 补充信息 | Additional Information

2024-01-15 14:53 UTC, arvinxx requested changes
另外相关单测补一下

2024-01-15 14:53 UTC, arvinxx commented on src/app/api/openai/stt/route.ts
> +    openai: openaiOrErrResponse as any,
为啥这里要加 any

2024-01-15 14:53 UTC, arvinxx commented on src/store/session/slices/session/selectors/list.ts
> +const sessionList = (sessionCustomGroups: SessionGroupItem[]) => (s: SessionStore) => {
这一段实现不应该在这里做。应该直接从 Service 里请求出来的就是分好组的

2024-01-15 14:53 UTC, arvinxx commented on src/store/global/slices/common/action.ts
这里拆一个 slice 出来吧，感觉不算 common

2024-01-15 14:53 UTC, arvinxx commented on src/database/models/__tests__/session.test.ts
> -    const updateData = { group: 'newGroup' };
为啥这个要改

2024-01-15 14:53 UTC, arvinxx commented on src/app/chat/features/SessionListContent/Modals/CreateGroupModal.tsx
> +import { preferenceSelectors } from '@/store/global/slices/common/selectors';
`@/store/global/selectors`

2024-01-15 14:53 UTC, arvinxx commented on src/app/chat/features/SessionListContent/Modals/ConfigGroupModal/index.tsx
> +import { preferenceSelectors } from '@/store/global/slices/common/selectors';
都检查下

2024-01-15 14:59 UTC, arvinxx commented
1. 不应该一进去默认折起：

<img width="788" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/54ba2f89-da3e-486a-a3d3-cae6b1f66557">


2. 顺序应该是默认列表在最下吧？

<img width="659" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/a36ec718-40d4-49fd-9bf9-af92af20209f">


3. 一个新分组如果是空的，是否需要显示下此分组内容为空？或者分组为空时，不允许展开？
<img width="473" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e4ffa1d1-32bf-4b14-8918-fb9ffaa202dd">

2024-01-15 15:04 UTC, arvinxx commented on src/store/global/slices/common/initialState.ts
> +    sessionCustomGroups: [],
这个参数不应该放在 preference 中，而是应该放到 settings。 settings 中的配置才会被导出。perference 的参数只是运行时偏好，不属于长期持久化数据

2024-01-15 15:59 UTC, canisminor1990 commented on src/store/session/slices/session/selectors/list.ts
> +const sessionList = (sessionCustomGroups: SessionGroupItem[]) => (s: SessionStore) => {
Service 部分你看下怎么搞？

2024-01-15 16:06 UTC, canisminor1990 commented on src/app/api/openai/stt/route.ts
> +    openai: openaiOrErrResponse as any,
我先把 openai 改成 ^4.22 了 你看看要不要再往上改

2024-01-15 16:13 UTC, arvinxx commented on src/store/session/slices/session/selectors/list.ts
> +const sessionList = (sessionCustomGroups: SessionGroupItem[]) => (s: SessionStore) => {
好

2024-01-15 16:13 UTC, arvinxx commented on package.json
> +    "openai": "^4.22",
最新的已经是 4.24 了

2024-01-16 01:25 UTC, Justin3go commented
之前阻止了modal中的默认点击事件：

```tsx
<div onClick={(e) => e.stopPropagation()}>
  <Modal.....
 </ div>
```
是因为弹窗也属于Dropdown，如果不阻止会出现以下情况（下方视频包含修改后-->修改前的对比）：

https://github.com/lobehub/lobe-chat/assets/63507251/cfaf144d-6616-490c-b462-d090fbde15bd

用文字描述就是在弹窗中点击也会触发切换当前会话的事件，看是否属于预期现象?

[相关PR](https://github.com/lobehub/lobe-chat/pull/1058)

2024-01-16 02:51 UTC, arvinxx commented
> 之前阻止了modal中的默认点击事件：
> 
> ```tsx
> <div onClick={(e) => e.stopPropagation()}>
>   <Modal.....
>  </ div>
> ```
> 
> 是因为弹窗也属于session Item，如果不阻止会出现以下情况（下方视频包含修改后-->修改前的对比）：
> 
>  demo.mp4 
> 用文字描述就是在弹窗中点击也会触发切换当前会话的事件，看是否属于预期现象?
> 
> [相关PR](https://github.com/lobehub/lobe-chat/pull/1058)

感觉要阻止的。这个是不是应该放进 Modal 组件里

2024-01-16 03:18 UTC, canisminor1990 commented
> > 之前阻止了modal中的默认点击事件：
> > ```tsx
> > <div onClick={(e) => e.stopPropagation()}>
> >   <Modal.....
> >  </ div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是因为弹窗也属于session Item，如果不阻止会出现以下情况（下方视频包含修改后-->修改前的对比）：
> > demo.mp4
> > 用文字描述就是在弹窗中点击也会触发切换当前会话的事件，看是否属于预期现象?
> > [相关PR](https://github.com/lobehub/lobe-chat/pull/1058)
> 
> 感觉要阻止的

需要用 div 包裹么 还是直接挂在弹窗也行？

2024-01-16 03:21 UTC, Justin3go commented
> 需要用 div 包裹么 还是直接挂在弹窗也行？

@canisminor1990 之前试了是因为会报类型错误，Modal上没这个属性：

![image](https://github.com/lobehub/lobe-chat/assets/63507251/1f8823a6-1599-475c-8ce9-4bb41a2c29d6)

2024-01-16 04:09 UTC, arvinxx commented
> 当导入的助手分组不存在时，自动移动到默认列表

这个逻辑有问题，导入的分组不存在时，应该自动创建这个分组。

2024-01-16 04:24 UTC, arvinxx requested changes

2024-01-16 04:24 UTC, arvinxx commented on package.json
> +    "sharp": "^0.33",
这个不能改，特地锁了的，升级了会报错： https://github.com/lobehub/lobe-chat/issues/1037

目前Vercel 还没解决：https://github.com/orgs/vercel/discussions/5449

2024-01-16 04:28 UTC, arvinxx commented
> > 需要用 div 包裹么 还是直接挂在弹窗也行？
> 
> @canisminor1990 之前试了是因为会报类型错误，Modal上没这个属性：

我估计 modal 应该在文档流里没有实体 div 节点，所以估计没法有这个事件。

2024-01-16 05:22 UTC, canisminor1990 commented
> > 当导入的助手分组不存在时，自动移动到默认列表
> 
> 这个逻辑有问题，导入的分组不存在时，应该自动创建这个分组。

创建不了 session 只记录分组id 不会记录分组名称，而且导入自己的数据一般都是全套导入不存在这个问题，一般都是导入别人分享的某个助手才会遇到分组不存在

2024-01-16 06:41 UTC, arvinxx commented
> > > 当导入的助手分组不存在时，自动移动到默认列表
> > 
> > 
> > 这个逻辑有问题，导入的分组不存在时，应该自动创建这个分组。
> 
> 创建不了 session 只记录分组id 不会记录分组名称，而且导入自己的数据一般都是全套导入不存在这个问题，一般都是导入别人分享的某个助手才会遇到分组不存在

要么就是这个数据结构的设计问题，比如别人导出的助手是不是应该也把分组带上？

2024-01-16 07:22 UTC, canisminor1990 commented
> > > > 当导入的助手分组不存在时，自动移动到默认列表
> > > 
> > > 
> > > 这个逻辑有问题，导入的分组不存在时，应该自动创建这个分组。
> 
> > 创建不了 session 只记录分组id 不会记录分组名称，而且导入自己的数据一般都是全套导入不存在这个问题，一般都是导入别人分享的某个助手才会遇到分组不存在
> 
> 要么就是这个数据结构的设计问题，比如别人导出的助手是不是应该也把分组带上？
> 
> 以及要不要支持导出一个分组的助手？

暂时感觉可以放放，可以先写个 todo

2024-01-16 10:29 UTC, arvinxx commented
这个不能放，得先讨论清楚，涉及到核心数据结构的问题了，上线了就不好改了。

到底应该把 group 数据存 settings ，还是作为sessions的一个子类单独开一个表存。这两个方式的实现策略是不一样的，影响方式也不一样。

如果是作为 settings 存，就会出现导出助手时候没有带上 group，导致会需要存入默认列表

同时这种方式也不支持直接导出一个分组的助手且保留分组。比如你导出一个写作分组，别人导入就全进到了默认分组，而不是给别人创建一个写作分组。

现有的导出机制不太可能为了 group 这一个字段做额外兼容。所以放 settings 会对未来功能的实现有限制。

2024-01-16 11:01 UTC, arvinxx commented
> 我倾向于可以在分组内导入导出助手，而不是导出时包含分组数据

这个实现成本感觉比导出时包含分组要高很多。

因为在分组里导入就要在导入的时候识别是哪个分组，然后再导入过程中再去修改它的 group 字段为指定id。需要额外开发一个action + 一个 service 的接口+ 一个数据库层的变更方法。

而如果是导入导出的时候包含分组数据，现有的链路不用做改动，只要加个分组字段就支持了。

2024-01-16 11:29 UTC, canisminor1990 commented
现在的聚合方案不行么

2024-01-18 13:43 UTC, canisminor1990 commented
@Justin3go 欢迎来我们的 Discord 开发频道聊天啊~❤

2024-01-19 12:29 UTC, arvinxx commented on package.json
> +    "zustand": "^4",
像这种地方不应该改掉。应该用 `^4.4`

原因是现在在用的 zustand  `createWithEqualityFn` 方法是 4.4 版本起才会有的。

虽然 ^4 能安装到最新版。但丢失了最小所依赖版本的语义。

如果有人用 pnpm 的 `resolution-mode` 为 lowest，装完这里运行就会报错。

2024-01-21 13:41 UTC, arvinxx commented
@canisminor1990 ContextMenu 的改动需要单独拆出来。我测试了下 iOS，并不支持长按唤起 ContextMenu。

2024-01-21 14:00 UTC, arvinxx commented on package.json
> +    "sharp": "^0.33",
https://github.com/lobehub/lobe-chat/pull/1041 看上去已经好了。应该新版修复了

2024-01-21 14:03 UTC, arvinxx commented
为减少 PR 变更量，i18n 和前置单测抽取到： https://github.com/lobehub/lobe-chat/pull/1119/files

2024-01-24 07:48 UTC, arvinxx approved these changes
此功能的完整开发介绍指南： https://github.com/lobehub/lobe-chat/wiki/Feature-Development.zh-CN

2024-01-24 08:38 UTC, merged