📝 docs: update docker auto-update script
lobehub/lobehub pull request #1165
Opened 2024-01-27 22:54 UTC by zhuozhiyongde

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [x] 📝 docs

#### 🔀 变更说明 | Description of Change

添加了一个自动更新的脚本，其可以自动拉取最新镜像并构建，然后移除旧的镜像。

#### 📝 补充信息 | Additional Information

2024-01-27 22:56 UTC, zhuozhiyongde commented
注：此脚本已经经过测试。

2024-01-28 04:03 UTC, arvinxx requested changes
看看启动指令那块有没有更好的实现方案？

2024-01-28 04:03 UTC, arvinxx commented on docs/Deployment/Docker-Deployment.zh-CN.md
> +echo "Started: $(docker run -d --network=host -e OPENAI_API_KEY=sk-xxx --name=Lobe-Chat --restart=always lobehub/lobe-chat)"
这段逻辑不太好，如果是希望提供给用户一键可以使用的指令，那么关于docker 环境变量的内容应该单独提取一个文件来加载，或者使用 `docker-compose.yml`，这样一来，这个 sh 的脚本对于不太懂开发的用户来说就能一键启用。

2024-01-28 04:06 UTC, zhuozhiyongde commented
> 看看启动指令那块有没有更好的实现方案？

说得有道理，但我有点不太知道怎么抽出来，也许可以把变量提取到脚本初始位置（？

我感觉 docker-compose.yml 的问题是不太好让 crontab 来定期执行。

2024-01-28 04:07 UTC, zhuozhiyongde commented on docs/Deployment/Docker-Deployment.zh-CN.md
> +echo "Started: $(docker run -d --network=host -e OPENAI_API_KEY=sk-xxx --name=Lobe-Chat --restart=always lobehub/lobe-chat)"
在提取一个文件我就感觉有些略显麻烦了（

2024-01-28 04:23 UTC, arvinxx commented
> 说得有道理，但我有点不太知道怎么抽出来，也许可以把变量提取到脚本初始位置（？

思路上比较好的方式应该是脚本与变量分离开来。比如有一个文件叫 `.env` 存这些环境变量，然后脚本里需要实现的就是读取 `.env` 的变量然后替换为对应的 Docker 变量。这样用户只需要修改 `.env` 这个变量就好了。

> 我感觉 docker-compose.yml 的问题是不太好让 crontab 来定期执行。

为啥不太好让 crontab 来定期执行？

比如我本地已经有一个写好的 `docker-compose.yml`:

```yml
version: '3.8'
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      OPENAI_API_KEY: sk-xxxx
      OPENAI_PROXY_URL: https://api-proxy.com/v1
      ACCESS_CODE: lobe66
```

那么用户需要执行的命令就是 进入到这个文件所在目录，然后执行 `docker-compose up`。 

那换成下面这样是不是就可以了？

```
echo "Started: $(docker-compose up)"
```

2024-01-28 10:03 UTC, zhuozhiyongde commented
> > 说得有道理，但我有点不太知道怎么抽出来，也许可以把变量提取到脚本初始位置（？
> 
> 思路上比较好的方式应该是脚本与变量分离开来。比如有一个文件叫 `.env` 存这些环境变量，然后脚本里需要实现的就是读取 `.env` 的变量然后替换为对应的 Docker 变量。这样用户只需要修改 `.env` 这个文件里的变量就好了。
> 
> > 我感觉 docker-compose.yml 的问题是不太好让 crontab 来定期执行。
> 
> 为啥不太好让 crontab 来定期执行？
> 
> 比如我本地已经有一个写好的 `docker-compose.yml`:
> 
> ```yaml
> version: '3.8'
> services:
>   lobe-chat:
>     image: lobehub/lobe-chat
>     container_name: lobe-chat
>     restart: always
>     ports:
>       - '3210:3210'
>     environment:
>       OPENAI_API_KEY: sk-xxxx
>       OPENAI_PROXY_URL: https://api-proxy.com/v1
>       ACCESS_CODE: lobe66
> ```
> 
> 那么用户需要执行的命令就是 进入到这个文件所在目录，然后执行 `docker-compose up`。
> 
> 那换成下面这样是不是就可以了？
> 
> ```
> echo "Started: $(docker-compose up)"
> ```

喔这样，我还以为是要把后面的删除什么的也全部搞进 docker-compose。

我待会整一下。

2024-01-28 16:09 UTC, zhuozhiyongde commented
@arvinxx 已更新。

2024-01-30 10:49 UTC, zhuozhiyongde commented
@arvinxx 想问下有没有更新的进展。

顺带，我看到一个库似乎也能做这个：https://github.com/containrrr/watchtower

2024-01-30 11:13 UTC, arvinxx commented
@zhuozhiyongde 哦不好意思 忘记回复了，我感觉是可以合了，你说的这个新的是什么？

2024-01-30 11:33 UTC, arvinxx approved these changes

2024-01-30 11:52 UTC, zhuozhiyongde commented
@arvinxx 哦就也是一个自动更新镜像的东西（

2024-01-30 13:17 UTC, merged