🐛 fix: The bottom safe area height of iOS
lobehub/lobehub pull request #1181
Opened 2024-01-29 18:43 UTC by mushan0x0

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Close: #387

修复之后的高度

<img width="364" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/a9a0325a-a720-4d4e-b2bf-5d48016f9a38">

<img width="364" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/f0e42a1d-d661-4ce6-85e2-2c06ec5246e8">

#### 📝 补充信息 | Additional Information

2024-01-30 11:32 UTC, arvinxx requested changes

2024-01-30 11:32 UTC, arvinxx commented on src/styles/global.ts
> +      height: ${isPWA ? '100vh' : '100%'} !important;
这个会导致开屏时页面跳动，有问题

2024-01-30 16:23 UTC, mushan0x0 commented on src/styles/global.ts
> +      height: ${isPWA ? '100vh' : '100%'} !important;
明天我改下

2024-01-31 03:30 UTC, arvinxx commented
@mushan0x0 还是会闪

2024-01-31 19:50 UTC, mushan0x0 commented
> @mushan0x0 还是会闪

明天我看下

2024-03-19 02:49 UTC, merged