feat: Support multiple API Keys
lobehub/lobehub pull request #1345
Opened 2024-02-21 09:30 UTC by luoweihua7

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

[[RFC] 027 - API Key 字段支持使用多个Key](https://github.com/lobehub/lobe-chat/discussions/1287)

启动时支持传入多个API Keys，通过Key之间使用**英文逗号**分割。接口调用时，API Keys支持随机（random）或者轮训（turn）方式获取。

增加参数 `API_KEY_SELECT_MODE`，用于控制Keys的选择模式。参数说明

- `random` 随机从提供的Keys中获取一个
- `turn` 按照提供的Keys顺序轮训获取
- `其他值` 使用第一个Key（注：空字符串也属于其他值的一种）
- 不配置参数，使用 `random` 随机模式

#### 📝 补充信息 | Additional Information

暂不支持请求失败时，使用下一个Key重新发起请求。

2024-02-21 14:31 UTC, arvinxx requested changes
麻烦按照 review 优化下实现~

2024-02-21 14:31 UTC, arvinxx commented on src/app/api/chat/[provider]/agentRuntime.ts
> +import keyMgr from '../keyManager';
使用全称 `apiKeyManager` ，缩写并不易于理解

2024-02-21 14:31 UTC, arvinxx commented on src/app/api/chat/[provider]/agentRuntime.ts
> +    const apiKey = payload?.apiKey || keyMgr.pick(OPENAI_API_KEY, API_KEY_SELECT_MODE);
`API_KEY_SELECT_MODE`  应该直接写在 apiKeyManager 的 pick 方法里，这样 pick 只要一个入参即可。

2024-02-21 14:31 UTC, arvinxx commented on src/app/api/chat/keyManager.ts
需要为其补充一下单元测试

2024-02-22 03:16 UTC, luoweihua7 commented on src/app/api/chat/[provider]/agentRuntime.ts
> +import keyMgr from '../keyManager';
已处理，同时将keyManager文件命名为apiKeyManager

2024-02-22 03:16 UTC, luoweihua7 commented on src/app/api/chat/[provider]/agentRuntime.ts
> +    const apiKey = payload?.apiKey || keyMgr.pick(OPENAI_API_KEY, API_KEY_SELECT_MODE);
已处理

2024-02-22 03:17 UTC, luoweihua7 commented on src/app/api/chat/keyManager.ts
已添加测试文件并验证通过

2024-02-22 06:25 UTC, arvinxx commented on src/app/api/chat/[provider]/agentRuntime.ts
> +    const apiKey = payload?.apiKey || apiKeyManager.pick(OPENAI_API_KEY);
这样实现还有个问题，就是相当于只支持后端的 apikey 轮询了，你认为应该只考虑后端apikey 轮询，还是也支持前端 apikey 轮询？

2024-02-22 08:22 UTC, luoweihua7 commented on src/app/api/chat/[provider]/agentRuntime.ts
> +    const apiKey = payload?.apiKey || apiKeyManager.pick(OPENAI_API_KEY);
的确，客户端也是可以填写多个API Key的。已处理。同时处理了AZURE_API_KEY也提供多个API Key的情况，辛苦再cr看看

2024-02-23 02:46 UTC, arvinxx commented on src/app/api/chat/[provider]/agentRuntime.ts
> +    const azureApiKey = apiKeyManager.pick(payload.apiKey || AZURE_API_KEY);
是不是写在最后一步比较好？这样只需要 pick 一次

```ts
const openaiApiKey = payload?.apiKey || OPENAI_API_KEY;
const azureApiKey = payload.apiKey || AZURE_API_KEY;

const apiKey = apiKeyManager.pick(useAzure ? azureApiKey : apiKey)
```

2024-02-26 03:25 UTC, luoweihua7 commented on src/app/api/chat/[provider]/agentRuntime.ts
> +    const azureApiKey = apiKeyManager.pick(payload.apiKey || AZURE_API_KEY);
是我着急了，已修改

2024-02-27 05:48 UTC, arvinxx approved these changes
LGTM, I'll merge it. Great work~

2024-02-27 05:48 UTC, merged