Fix/ollama checker
lobehub/lobehub pull request #1397
Opened 2024-02-27 02:17 UTC by sjy

#### 💻 变更类型 | Change Type

- [ x] ✨ feat
- [x ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

- https://github.com/lobehub/lobe-chat/issues/1351
- https://github.com/lobehub/lobe-chat/issues/1352

#### 📝 补充信息 | Additional Information

<img width="854" alt="image" src="https://github.com/lobehub/lobe-chat/assets/1523060/31bbc40f-6823-4d8e-920d-2c37fe98427b">
<img width="609" alt="image" src="https://github.com/lobehub/lobe-chat/assets/1523060/70a34554-4280-4d31-879a-46cd46c8e2d9">

2024-02-27 05:55 UTC, arvinxx requested changes
还没全看完，粗看了下，有些细节先调整下

2024-02-27 05:55 UTC, arvinxx commented on src/app/settings/llm/components/Checker.tsx
> +    if (provider === 'ollama') {
ollama 的实现建议单独做一个 Ollama Checker ，不要揉进通用 Checker 里， 或者把 check 方法做成一个props也行

2024-02-27 05:55 UTC, arvinxx commented on src/app/settings/llm/components/ModelSelector.tsx
> +  useEffect(() => {
不要使用 useEffect，改成用 useSWR 来获取数据

2024-02-27 05:55 UTC, arvinxx commented on src/services/ollama.ts
> +    fetch(`${API_ENDPOINTS.ollama}/list?endpoint=${params.endpoint}`);
`API_ENDPOINTS.ollamaList` 而不是 `${API_ENDPOINTS.ollama}/list` ，将所有 url 都完整写到 `_url` 文件里，这样便于知道所有的 url 有哪些

2024-02-27 11:25 UTC, sjy commented on src/app/settings/llm/components/Checker.tsx
> +    if (provider === 'ollama') {
我在想，下面的列表组件会发请求，这个checker 还是否有必要存在

2024-02-27 15:57 UTC, arvinxx commented on src/app/settings/llm/components/Checker.tsx
> +    if (provider === 'ollama') {
有必要的。第一次进去出错，然后本地起来，然后用户的直觉上是再去点下 check 。 虽然功能能满足，但是用户行为习惯是不一样的。就像Chrome 的收藏夹一样：

<img width="487" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/bbd6f1e0-5b22-4573-b6f8-908f481387ac">

当你点击的时候已经完成收藏了，但大部分人的习惯还是会去点下「完成」来确认收藏。

2024-02-29 05:27 UTC, sjy commented on src/app/settings/llm/components/ModelSelector.tsx
> +  useEffect(() => {
这个改了，不过需要讨论是
- 这里的列表选项和初始值设定逻辑，在另一个话题下回复了；
- 选项渲染UI要不要和 ModelSelect那边对齐，获得一致的操作体验

2024-03-10 11:40 UTC, arvinxx commented on src/services/ollama.ts
> +  getOllamaClient = () => {
为何不直接 constructor 里初始化呢？

2024-03-10 13:44 UTC, arvinxx commented on src/services/ollama.ts
> +      response = createErrorResponse(ChatErrorType.ServiceUnavailable, {
我建议新增一个 Ollama 的 error 类型，然后针对这个类型展示明确的 Ollama 未启动的提示。

<img width="1043" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/338e85be-b1c6-4b29-92ab-71e867cc660d">

现在这样看上去对用户来说不太友好，不一定清楚具体发生了啥。真正有用的信息反而是 'please check whether your ollama service is available' 这条

2024-03-10 13:44 UTC, arvinxx commented on src/app/settings/llm/Ollama/Checker.tsx
这个问题要一并处理下，之前也有遇到。同时显示检查通过与错误了

<img width="1075" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/cb6bd4d1-15b0-4230-99ed-9f32e7ed26ed">

2024-03-10 13:44 UTC, arvinxx commented on src/features/Conversation/Error/InvalidOllamaModel.tsx
<img width="560" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/dcb8a8cf-c83b-4edd-a190-508aa95c2084">

最好是上面的「请求 Ollama 服务出错，请根据以下信息排查或重试」这条信息改为「未找到该本地模型，请通过 Ollama 下载后重试」

2024-03-10 13:44 UTC, arvinxx commented on src/features/Conversation/Error/InvalidOllamaModel.tsx
「拉取」 改为 「下载」

2024-03-10 13:44 UTC, arvinxx commented on src/features/Conversation/Error/InvalidOllamaModel.tsx
<img width="421" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/53de3adf-e80a-4030-998d-52d017a3cb82">

这块样式我后续优化下，基础体验是 OK 的。要是可以的话后续最好把下载速度和预计剩余时间也加下。

2024-03-11 01:57 UTC, sjy commented on src/services/ollama.ts
> +  getOllamaClient = () => {
ollama-js 设置配置只放在了构造函数环节

2024-03-11 02:00 UTC, arvinxx commented on src/services/ollama.ts
> +  getOllamaClient = () => {
哦 我知道了，因为要读settings 的url 是吧

2024-03-11 02:02 UTC, sjy commented on src/services/ollama.ts
> +  getOllamaClient = () => {
Yes

2024-03-11 03:44 UTC, sjy commented on src/features/Conversation/Error/InvalidOllamaModel.tsx
第一个暂时不改吧，目前通过 agentruntime 错误码判断，错误来源可能是多种的，比如这种，
<img width="460" alt="image" src="https://github.com/lobehub/lobe-chat/assets/1523060/35260ef6-5281-429b-8af1-8b6e9c524a79">
卡片内的文案会提示具体的原因，应该可以帮助用户理解到
下载速度和剩余时间我再单独 commit

2024-03-13 02:32 UTC, arvinxx requested changes
其他我感觉差不多了，后续要调整的我再给改改。

2024-03-13 02:32 UTC, arvinxx commented on src/app/settings/llm/Ollama/Checker.tsx
> +  const { data, error, loading, run } = useRequest(ollamaService.getModels, { manual: true });
emmm 要是用 `useRequest` 不如改回 `useSWR` 😂 。useRequest 现在已经没有人维护了

2024-03-13 02:32 UTC, arvinxx commented on src/hooks/useDownloadMonitor.ts
这个方法有点 hack 了，相当于只为 ollama 的下载而显示的速度，不够通用。我建议放到 `Error/InvalidOllamaModel` 目录下。原本的 `InvalidOllamaModel.tsx` 改成 `InvalidOllamaModel/index.tsx`

2024-03-13 03:25 UTC, sjy commented on src/app/settings/llm/Ollama/Checker.tsx
> +  const { data, error, loading, run } = useRequest(ollamaService.getModels, { manual: true });
主要是想直接用 error，loading 状态，没有用fetch，那我转回 swr 吧

2024-03-13 03:26 UTC, sjy commented on src/hooks/useDownloadMonitor.ts
嗯，设计上是考虑在 React Hooks场景下的通用，我还是转到你建议的目录吧

2024-03-15 14:16 UTC, arvinxx commented
优化了一版下载样式：

<img width="497" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/a38fea77-e4e5-4e9d-9db8-4981fdf317ed">

但同样发现了一些问题:
1. 用户不知道模型本身有多大，不知道当前下载了多少尺寸了；
2. 如果是中途断点下载，那么下载的速度会不准。
3. 不支持取消下载；
4. 下载过程中允许关闭提示可能不太合理。

2024-03-15 14:19 UTC, arvinxx approved these changes
上面提到的几个点是进一步的优化项，这一版我觉得可以先合了~

2024-03-15 14:47 UTC, merged

2024-03-21 03:05 UTC, sjy commented
> 优化了一版下载样式：
> 
> <img alt="image" width="497" src="https://private-user-images.githubusercontent.com/28616219/313223044-a38fea77-e4e5-4e9d-9db8-4981fdf317ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTA1MTAsIm5iZiI6MTcxMDk5MDIxMCwicGF0aCI6Ii8yODYxNjIxOS8zMTMyMjMwNDQtYTM4ZmVhNzctZTRlNS00ZTlkLTlkYjgtNDk4MWZkZjMxN2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAzMDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTZmMzc5NDg0M2I3OGY1MzM0N2MxNmVmOGFlM2JjMGZkNmUwYjUwNTU2MzA4ZWNiZDZiNjE3ZTRlYzBkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K2LDvDZmQkUD-emCFCwWnxlZnA0WRS3UQjJc45PhYR0">
> 但同样发现了一些问题:
> 
> 1. 用户不知道模型本身有多大，不知道当前下载了多少尺寸了；
> 2. 如果是中途断点下载，那么下载的速度会不准。
> 3. 不支持取消下载；
> 4. 下载过程中允许关闭提示可能不太合理。



> 优化了一版下载样式：
> 
> <img alt="image" width="497" src="https://private-user-images.githubusercontent.com/28616219/313223044-a38fea77-e4e5-4e9d-9db8-4981fdf317ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTA1MTAsIm5iZiI6MTcxMDk5MDIxMCwicGF0aCI6Ii8yODYxNjIxOS8zMTMyMjMwNDQtYTM4ZmVhNzctZTRlNS00ZTlkLTlkYjgtNDk4MWZkZjMxN2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAzMDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTZmMzc5NDg0M2I3OGY1MzM0N2MxNmVmOGFlM2JjMGZkNmUwYjUwNTU2MzA4ZWNiZDZiNjE3ZTRlYzBkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K2LDvDZmQkUD-emCFCwWnxlZnA0WRS3UQjJc45PhYR0">
> 但同样发现了一些问题:
> 
> 1. 用户不知道模型本身有多大，不知道当前下载了多少尺寸了；
> 2. 如果是中途断点下载，那么下载的速度会不准。
> 3. 不支持取消下载；
> 4. 下载过程中允许关闭提示可能不太合理。

Create another PR here: https://github.com/lobehub/lobe-chat/pull/1659/checks