✨add: Support 01-AI Models
lobehub/lobehub pull request #1627
Opened 2024-03-18 16:25 UTC by MapleEve

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

根据 Discussion 的步骤添加了零一万物的 API （因为是完全兼容 OpenAI 的所以难度不大）

不支持 FC

#### 📝 补充信息 | Additional Information

由于缺乏 Component 中的定义，所以需要补全 01AI的图标、设置页Logo才能正常显示

2024-03-19 01:56 UTC, MapleEve commented
目前的编译错误有：
```
TypeError: Cannot read properties of undefined (reading 'Text')
```
因为引用的 `@lobehub/icons` 不包含 ZeroOne

2024-03-20 05:34 UTC, MapleEve commented
![image](https://github.com/lobehub/lobe-chat/assets/1845053/c7394058-f4cf-42fb-9a6c-879681d4112c)
![image](https://github.com/lobehub/lobe-chat/assets/1845053/07d5cb80-0cde-436b-b270-5c153600830a)

修改完成了

2024-03-20 05:40 UTC, MapleEve commented
![image](https://github.com/lobehub/lobe-chat/assets/1845053/a333539a-4a31-47b4-aa4c-d7766fa883e7)
Vision

2024-03-21 05:47 UTC, arvinxx commented
赞啊 👍🏻 ，等我把 sync 搞完就来 review~

2024-03-22 16:38 UTC, arvinxx requested changes
根据review 调整下~

2024-03-22 16:38 UTC, arvinxx commented on locales/en-US/common.json
locale 都写在 `src/locales/xxx` 里，这样以后调用 `npm run i18n` 能自动生成其他所有语种的 json

2024-03-22 16:38 UTC, arvinxx commented on src/app/settings/llm/Anthropic/index.tsx
这里要动的理由是啥？我感觉不需要改

2024-03-22 16:38 UTC, arvinxx commented on src/app/settings/llm/Groq/index.tsx
这些都不需要改吧

2024-03-22 16:38 UTC, arvinxx commented on src/components/ModelIcon/index.tsx
> +  if (model.startsWith('qwen')) return <Tongyi.Avatar background={Tongyi.colorPrimary} size={size} />;
这样会有个问题，如果是 model 是 `huggingface/qwen` 这种就匹配不到了。还是用 includes 吧

2024-03-22 17:00 UTC, MapleEve commented on locales/en-US/common.json
好的明天我改下

2024-03-22 17:00 UTC, MapleEve commented on src/app/settings/llm/Anthropic/index.tsx
没带Models 的logo会不会有人不知道这个是Claude

2024-03-22 17:01 UTC, MapleEve commented on src/app/settings/llm/Groq/index.tsx
这个主要和其它（上下）的模型标识一致，都是模型Logo+名称

2024-03-23 04:50 UTC, arvinxx commented on src/app/settings/llm/Anthropic/index.tsx
应该不会，不知道 Anthropic 的人大概率更不懂 Claude 的 Logo 是啥

2024-03-23 18:51 UTC, MapleEve commented on src/components/ModelIcon/index.tsx
> +  if (model.startsWith('qwen')) return <Tongyi.Avatar background={Tongyi.colorPrimary} size={size} />;
done

2024-03-23 18:55 UTC, MapleEve commented on src/app/settings/llm/Anthropic/index.tsx
先还原了吧，不过还是有好多人都不知道Claude怎么设置。因为这些人只知道有Claude而不知道是Anthropic的

2024-03-23 19:06 UTC, MapleEve commented on locales/en-US/common.json
done

2024-03-25 03:40 UTC, arvinxx reviewed
那个地方再调整下，其他没问题

2024-03-25 03:40 UTC, arvinxx commented on src/app/settings/llm/Groq/index.tsx
> +      title={<Groq.Combine color={theme.isDarkMode ? theme.colorText : Groq.colorPrimary} size={24} />}
此处我感觉是Text 比 Combine 美观，换回来吧

2024-03-25 03:58 UTC, MapleEve commented on src/app/settings/llm/Groq/index.tsx
> +      title={<Groq.Combine color={theme.isDarkMode ? theme.colorText : Groq.colorPrimary} size={24} />}
done

2024-03-25 11:48 UTC, arvinxx approved these changes
LGTM, I'll merge it.

2024-03-25 11:56 UTC, merged