added Bulgarian translation
lobehub/lobehub pull request #1732
Opened 2024-03-25 13:22 UTC by pazoff

- [*] ✨ feat

#### 🔀 变更说明 | Description of Change

added Bulgarian translation

#### 📝 补充信息 | Additional Information

Bulgarian translation

2024-03-26 13:48 UTC, arvinxx commented
@pazoff hi pazoff ! I'm really glad for your contribution, cloud you pelease check the document [Add New Locale](https://github.com/lobehub/lobe-chat/wiki/Add-New-Locale) ? I think there is some more work need to be done~

2024-03-26 17:17 UTC, pazoff commented
> @pazoff hi pazoff ! I'm really glad for your contribution, cloud you pelease check the document [Add New Locale](https://github.com/lobehub/lobe-chat/wiki/Add-New-Locale) ? I think there is some more work need to be done~

bg_BG added to .i18nrc.js

2024-03-28 17:01 UTC, arvinxx commented
@pazoff Hi pazoff~ sorry for the delay reply. Could you please add the last and also the most important part for users:

add the locale option:

https://github.com/lobehub/lobe-chat/blob/69fcc78aaa0e39501ce5d490746af81ac7c92d15/src/locales/resources.ts#L107-L114

2024-03-28 17:18 UTC, pazoff commented
> @pazoff Hi pazoff~ sorry for the delay reply. Could you please add the last and also the most important part for users —— the Bulgarian locale option:
> 
> https://github.com/lobehub/lobe-chat/blob/69fcc78aaa0e39501ce5d490746af81ac7c92d15/src/locales/resources.ts#L107-L114

added bg_BG

2024-03-28 17:22 UTC, arvinxx requested changes
some detail need to be polished

2024-03-28 17:22 UTC, arvinxx commented on src/locales/resources.ts
> +  'bg_BG',
it should be `bg-BG`

2024-03-28 17:22 UTC, arvinxx commented on src/locales/resources.ts
> +    label: 'Bulgarian',
Why not use the Bulgarian language to display "Bulgarian" ?

2024-03-28 17:22 UTC, arvinxx commented on src/locales/resources.ts
> +    value: 'bg_BG',
bg-BG

2024-03-28 17:42 UTC, arvinxx approved these changes
LGTM now, I'll merge it. Thanks for your contribution!

2024-03-28 17:55 UTC, merged