🐛 fix: ollama LLaVA models enable vision
lobehub/lobehub pull request #1791
Opened 2024-03-28 14:29 UTC by wuyuan1992

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change
- 修复 Ollama LLaVA 上传图片报错的问题
- 修复 UI 界面选择 LLaVA 后无法选择图片的问题

#### 📝 补充信息 | Additional Information
关联 issues: 
- fix: https://github.com/lobehub/lobe-chat/issues/1482
- fix: https://github.com/lobehub/lobe-chat/issues/1416

2024-03-28 16:59 UTC, arvinxx commented
有没有测试截图？以及能不能补下单元测试？

2024-03-29 04:08 UTC, wuyuan1992 commented
- 已添加测试用例
- 测试截图
1. 已可以上传图片且不会报错，
2. 可检测到增加了 images 字段。
但解析似乎文不对题，不确定是否 ollama 还是模型本身的问题
![image](https://github.com/lobehub/lobe-chat/assets/20351654/dca9eaa7-7fec-41d7-a50b-cc1221a8f741)
![image](https://github.com/lobehub/lobe-chat/assets/20351654/2b6caf5a-586e-4ad3-a925-74550737ffcd)

2024-03-29 05:47 UTC, arvinxx commented
> 模型本身的问题

文不对题一般是模型本身质量问题。7B、13B 的小模型一般能力都有限的

2024-03-29 05:49 UTC, arvinxx requested changes
最后一点需要调整的地方

2024-03-29 05:49 UTC, arvinxx commented on src/libs/agent-runtime/ollama/index.ts
> +import { OpenAIChatMessage } from '@/types/openai/chat';
这里的类型不要用 @/type 引入，从 libs/agent-runtime/types 里引。后续这个包会抽成独立模块，引 `@/types` 会有问题。

`OllamaChatMessage` 的类型也单独放在这个目录下

2024-03-29 06:23 UTC, arvinxx approved these changes
LGTM now, Thanks for your contribution~

2024-03-29 06:24 UTC, merged

2024-03-30 02:53 UTC, Xscut commented
使用34B模型依旧文不对题

2024-05-06 12:24 UTC, wwjCMP commented
Cannot upload images using the LLaVA 34B model.

2024-05-14 16:41 UTC, locknet11 commented
Running latest docker image I'm unable to upload images too. Using LLaVA 7B model