Add GitHub OAuth login method
lobehub/lobehub pull request #1850
Opened 2024-04-01 15:34 UTC by devcxl

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

添加Github OAuth 登陆方式

#### 📝 补充信息 | Additional Information

新增环境变量：`GITHUB_CLIENT_ID` `GITHUB_CLIENT_SECRET`

2024-04-01 15:41 UTC, arvinxx requested changes
请参考其他几个PR补充下文档：
- https://github.com/lobehub/lobe-chat/pull/1456
- https://github.com/lobehub/lobe-chat/pull/1143

2024-04-01 15:41 UTC, arvinxx commented on README.zh-CN.md
这个可以revert

2024-04-02 01:28 UTC, devcxl commented on README.zh-CN.md
OK

2024-04-02 04:36 UTC, devcxl commented
@arvinxx 文档已补充

2024-04-02 05:30 UTC, arvinxx commented
@devcxl OK，录个 demo 看一眼？

2024-04-02 05:57 UTC, devcxl commented
好了，看这个
https://github.com/lobehub/lobe-chat/assets/64475363/9edbe3af-349d-4de0-8efb-e721e6549000

2024-04-02 06:35 UTC, arvinxx approved these changes
LGTM, I'll merge it. Thanks for your contribution!

2024-04-02 06:35 UTC, merged

2024-04-02 06:53 UTC, devcxl commented
OK