feat: support minimax as provider
lobehub/lobehub pull request #2087
Opened 2024-04-18 11:46 UTC by lwshen

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Support model provider: Minimax

feat #1053

https://github.com/lobehub/lobe-chat/assets/5581972/3d3645eb-a290-4c92-8c87-4674f1b756d4

#### 📝 补充信息 | Additional Information

2024-04-18 12:05 UTC, arvinxx reviewed
感谢贡献！整体看下来没啥太大问题，个别自动生成的翻译需要调整下~

2024-04-18 12:05 UTC, arvinxx commented on locales/nl-NL/modelProvider.json
这个需要重跑下

2024-04-18 12:05 UTC, arvinxx commented on locales/tr-TR/modelProvider.json
这个也是

2024-04-18 12:05 UTC, arvinxx commented on locales/zh-TW/modelProvider.json
> +    "title": "極小化",
Minimax

2024-04-18 14:20 UTC, arvinxx commented
@lwshen 我测了下 apikey 的余额不足的情况下，没有抛错：

<img width="776" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/291f37ec-3f0f-4506-9801-d2ab77238de2">

这个是api接口本身就这样，没有返回错误码，还是实现问题？

2024-04-18 15:14 UTC, lwshen commented
> @lwshen 我测了下 apikey 的余额不足的情况下，没有抛错：
> 
> <img alt="image" width="776" src="https://private-user-images.githubusercontent.com/28616219/323641209-291f37ec-3f0f-4506-9801-d2ab77238de2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTAzMzIsIm5iZiI6MTcxMzQ1MDAzMiwicGF0aCI6Ii8yODYxNjIxOS8zMjM2NDEyMDktMjkxZjM3ZWMtM2YwZi00NTA2LTk4MDEtZDJhYjc3MjM4ZGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE0MjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZmJlM2JmMGI4NjI4N2RhMGNlOThlNTZmN2Y3YThiMThhODAxNTI0ZjcyNDU4M2UzZGM1ODE0M2U2NzI4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPO2NBRR262sn2qAocIPMdDZwNM1Hw0p2NhMpzUSEJ4">
> 这个是api接口本身就这样，没有返回错误码，还是实现问题？

```
< HTTP/2 200
<
* Connection #0 to host api.minimax.chat left intact
{"base_resp":{"status_code":1004,"status_msg":"token is unusable"}}
```

试了一下 api key 失效的情况，api 依旧返回了 200 的状态码

2024-04-19 01:42 UTC, arvinxx commented
这有点离谱… 有可能做兼容吗？

2024-04-19 07:43 UTC, lwshen commented
> 这有点离谱… 有可能做兼容吗？

更新了一下代码。

本来打算直接从 openai response 中读取内容，但是 api 返回的不是 SSE 格式，读取不到里面的内容。

因此，实现了一个 `MinimaxStream`，通过返回值中的 `status_code` 进行判断有没有错误，不过遇到了 `unhandledRejection` 错误，不知道你有没有什么想法？

```
⨯ unhandledRejection: {
  error: { code: 1004, message: 'token is unusable' },
  errorType: 'InvalidMinimaxAPIKey',
  provider: 'minimax'
}
```

2024-04-19 08:03 UTC, arvinxx commented on src/libs/agent-runtime/minimax/index.ts
> +      this.throwIfErrorResponse(fetchResponse.clone());
类似的问题我之前遇到过： https://github.com/lobehub/lobe-chat/discussions/737#discussioncomment-8336499 。详细的信息可以看之前的一个讨论：https://github.com/langchain-ai/langchainjs/issues/4015#issuecomment-1892176746

原因是这样： 

你在这里用了 `this.throwIfErrorResponse(fetchResponse.clone());` 没有加 await， 那么这就会使得这个事件的异步不会被 外层的 try catch 捕获。

我理解你的想法应该是想在stream之前先确保一下没有 error 对吧？如果没有 error 再接着进入 Stream 中。 但是如果给  `this.throwIfErrorResponse(fetchResponse.clone());` 前面加了 await ，那么如果遇到正常的 steam 又得等 stream 结束才行，就不符合预期。

我理解这个逻辑应该要做到 stream 解析的环节，就是上面那个 `parseMinimaxStream` 那里。 比如读到 `base_resp.status_code` 这个字段就意味着可能是有问题的，在那个阶段抛错，可能就可以被 catch 到

2024-04-19 08:23 UTC, lwshen commented on src/libs/agent-runtime/minimax/index.ts
> +      this.throwIfErrorResponse(fetchResponse.clone());
`AIStream` 只会解析 SSE 的结果，而当遇到 invalid api key 的时候，直接返回了普通的 response，导致 `parseMinimaxStream` 接收不到传入的数据。

或许需要自己实现一个 `CustomAIStream` 来实现上面的逻辑。

2024-04-19 08:35 UTC, arvinxx commented on src/libs/agent-runtime/minimax/index.ts
> +      this.throwIfErrorResponse(fetchResponse.clone());
我在前端其实是自己实现过了一个读 sse 的方案，逻辑上并不太复杂，可以看下是不是可以复用这块思路：

https://github.com/lobehub/lobe-chat/blob/main/src/utils/fetch.ts#L73-L92

2024-04-19 10:15 UTC, lwshen commented on src/libs/agent-runtime/minimax/index.ts
> +      this.throwIfErrorResponse(fetchResponse.clone());
复用了 `fetchSSE` 的 function。当 api key 不可用时，会显示错误提示。

<img width="1355" alt="image" src="https://github.com/lobehub/lobe-chat/assets/5581972/d85dd873-7509-4933-8619-82c5d14656a7">

2024-04-20 09:58 UTC, arvinxx commented
@lwshen 得 rebase 下代码了，上一个 PR #2041 调整了 AgentRuntime 的位置

2024-04-20 11:09 UTC, lwshen commented
> @lwshen 得 rebase 下代码了，上一个 PR #2041 调整了 AgentRuntime 的位置

done

2024-04-21 07:34 UTC, arvinxx commented
<img width="638" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/a8f8c04f-298b-4ec0-8475-1c96e3be7576">

我试了下还是有问题

2024-04-21 15:42 UTC, lwshen commented
> <img alt="image" width="638" src="https://private-user-images.githubusercontent.com/28616219/324230675-a8f8c04f-298b-4ec0-8475-1c96e3be7576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTM5NTMsIm5iZiI6MTcxMzcxMzY1MywicGF0aCI6Ii8yODYxNjIxOS8zMjQyMzA2NzUtYThmOGMwNGYtMjk4Yi00ZWMwLTg0NzUtMWM5NmUzYmU3NTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE1MzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZmI1ZGQ3ODVhMGY2Zjg2MmQyOGUyNjljNDZmNGI2MzY5YjgzYmM3NzcwMTQ0MjFmMTY1MjAxM2Y2OGE4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OWYHzrK4s4-v6Lt9bjMHsTG9Bu1r20BPcFm4NIu9lnA">
> 我试了下还是有问题

Fixed. 这里存在两个问题：
1. 出现 `TypeError: This ReadableStream did not return bytes.` 错误，解决方法：使用 `new TextEncoder().encode()` 进行编码。refer to: https://vercel.com/docs/functions/streaming/quickstart#add-content-to-your-stream
2. vercel 在 SSE response 从 `reader.read()` 中读取内容时，会把同一个 chunk 中的内容截断，变成两个 chunk，目前强制要求 minimax 使用 nodejs 而不是 edge runtime function 作为 workaround，期待有更好的解决方法

![Xnip2024-04-21_23-33-34](https://github.com/lobehub/lobe-chat/assets/5581972/9ec90583-2056-42ae-b324-b914cbf6cb92)
在这张截图中，可以看到，每次调用 `onMessageHandle` 的时候，除了第一次返回的结果是正确的，之后的结果都将理应是同一次的结果，分成了两次进行调用

2024-04-22 02:41 UTC, arvinxx reviewed
> vercel 在 SSE response 从 reader.read() 中读取内容时，会把同一个 chunk 中的内容截断，变成两个 chunk

这个问题是不是直接用 fetchSSE 读数据造成的问题呢？之前用 openai 的包似乎是正常的？

2024-04-22 02:41 UTC, arvinxx commented on src/libs/agent-runtime/minimax/index.ts
> +      const response = await fetchSSE(
我在想是不是 `fetchSSE` 这个逻辑是不是应该直接打平到这里的 chat 实现中？之前设想的复用 fetchSSE 是能简化掉中间的解析过程，但从 `onFinish` 和  `onMessageHandle` 现有的实现来看免不了处理很多 minmax 特有的逻辑，感觉不如移除这个 fetchSSE 的引入，直接基于 TextDecoder 来读，这样可能代码会更加精简一些？

2024-04-22 13:40 UTC, lwshen commented
改成了直接使用 fetch。

不知道 vercel 是不是对 openai 的包做过什么特别的优化，怀疑文档中的
> The Edge runtime provides a subset of Web APIs such as [fetch](https://developer.mozilla.org/docs/Web/API/Fetch_API), [Request](https://developer.mozilla.org/docs/Web/API/Request), and [Response](https://developer.mozilla.org/docs/Web/API/Response). This lightweight API layer is built to be performant and execute code with minimal latency.
> from [source](https://vercel.com/docs/functions/edge-middleware/edge-runtime)
有可能会导致这个问题，将其中一部分数据提前返回

2024-04-25 07:24 UTC, arvinxx commented
@lwshen 冲突merge下~

2024-04-25 07:59 UTC, arvinxx requested changes
实现还是有点问题，流式输出没了，变成了一次性输出

2024-04-25 07:59 UTC, arvinxx commented on src/libs/agent-runtime/minimax/index.ts
> +      while (!done) {
这一段实现有点问题。相当于先在服务端完成了所有流式解析，然后一次性输出了，导致效果是要等很久，然后一次性全部出来。

2024-04-25 10:28 UTC, lwshen commented on src/libs/agent-runtime/minimax/index.ts
> +      while (!done) {
exception 和 async function 杠上了。我现在是另外写了个 function，以同步的方式只处理第一次发过来的请求结果，如果有错误就 throw 出去。

2024-04-28 02:46 UTC, arvinxx commented on src/libs/agent-runtime/AgentRuntime.ts
> +import LobeMinimaxAI from '@/libs/agent-runtime/minimax';
代码风格改成 

import { LobeMinimaxAI } from './minimax';


这样吧~

2024-04-28 02:46 UTC, arvinxx commented on src/libs/agent-runtime/minimax/index.ts
> +  private async parseFirstResponse(reader: ReadableStreamDefaultReader<Uint8Array>) {
我感觉 parseFirstResponse 的实现应该可以直接合并到 parseResponse 吧？为什么需要把它单独提出来呢？

比如把抛错的部分也一并加到 `parseMinimaxResponse` 里。因为如果是第一个 chunk ，还不会进入 stream 里，所以如果直接在 parse 时抛错，应该就能直接抛出来。

2024-04-28 03:32 UTC, lwshen commented on src/libs/agent-runtime/minimax/index.ts
> +  private async parseFirstResponse(reader: ReadableStreamDefaultReader<Uint8Array>) {
经过测试，如果写在`parseMinimaxResponse`里面，就会因为是 async 的 function，从而出现`unhandledRejection`错误，无法正确 catch 住这个错误。

2024-04-28 15:36 UTC, arvinxx commented
@lwshen rebase 下 main ，其他我测下来没问题了~

2024-04-28 15:45 UTC, lwshen commented
@arvinxx done

2024-04-29 02:57 UTC, arvinxx approved these changes
LGTM now, I'll merge it. Thanks for your hard working! I'm really appraciate your great contribution! 👏

2024-04-29 02:57 UTC, merged