♻️  refactor: support more model Icons: dbrx, command-r, openchat, rwkv, Ber…
lobehub/lobehub pull request #2107
Opened 2024-04-19 19:00 UTC by MapleEve

…t-vits2, Stable Diffusion, WizardLM, adobe firefly, skylark

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [x] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change
根据  https://icons.lobehub.com/ 的现有资源以及 OpenRouter、Ollama的新增模型，增加了许多新模型的展示

#### 📝 补充信息 | Additional Information
本来想标注哪些的原始 Providers 是没有接入的，但是使用 map 会有 eslint 的字母序要求，所以先放个draft上来，看是决定还用if还是用map

2024-04-20 15:12 UTC, arvinxx requested changes
建议还是改回成 if 语法，由于 map 模式无法覆盖所有匹配的场景，始终存在需要  if 进行判断的情况，因此并不能真正降低维护心智。用 if 语法虽然看上去有点挫，但胜在易于理解。我觉得对于长期维护来说更适合一些。

2024-04-21 13:47 UTC, MapleEve commented
> 建议还是改回成 if 语法，由于 map 模式无法覆盖所有匹配的场景，始终存在需要 if 进行判断的情况，因此并不能真正降低维护心智。用 if 语法虽然看上去有点挫，但胜在易于理解。我觉得对于长期维护来说更适合一些。

好的，今天弄好

2024-04-21 17:18 UTC, arvinxx commented on src/components/ModelIcon/index.tsx
> +    return <Zhipu.Avatar background={Zhipu.colorPrimary} size={size} />;
这个应该仍然使用 GLM 的 Logo，智谱Logo不是用在Model上的，应该是用在 Provider 上。

2024-04-21 17:18 UTC, arvinxx commented on src/components/ModelTag/ModelIcon.tsx
> +  if (model.startsWith('d_') || model.startsWith('g_') || model.startsWith('wd_'))
ref 的部分放在 if 上面，这样看得清楚些

2024-04-21 17:18 UTC, arvinxx commented on src/components/ModelIcon/index.tsx
> +    return <Baichuan.Avatar background={Baichuan.colorPrimary} size={size} />;
加 `colorPrimary` 的最好贴下效果图，不然不好评估视觉样式，如果没有特殊原因，不需要加 background

2024-04-22 04:27 UTC, arvinxx commented
@MapleEve 构建挂了

2024-04-22 05:19 UTC, MapleEve commented
> @MapleEve 构建挂了
> 
> <img alt="image" width="1022" src="https://private-user-images.githubusercontent.com/28616219/324328282-6a08accf-a8bc-498b-8f85-e817e43dd97c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjMzMjcsIm5iZiI6MTcxMzc2MzAyNywicGF0aCI6Ii8yODYxNjIxOS8zMjQzMjgyODItNmEwOGFjY2YtYThiYy00OThiLThmODUtZTgxN2U0M2RkOTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1MTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZmU0Nzk4ODc4MjJiZmMwMTUyNTBiOGJkZjE0ZGJjMmEzMzM0N2U4YzE2MDM0NWJjNzNkNjgwY2ExMGUxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JoFBWWhTCWIebGIjLIw6II1xzeypwWJMnKGFvAqqi0o">

奇怪，eslint 和 sonoar 当时都没报错，现在应该好了。

2024-04-22 05:55 UTC, arvinxx requested changes

2024-04-22 05:55 UTC, arvinxx commented on src/components/ModelIcon/index.tsx
> +  if (model.startsWith('yi-')) return <Yi.Avatar size={size} />;
`startWith(yi-)` 有问题：

<img width="360" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/82b8b731-ef52-4b62-9569-6dfc6961d63b">

2024-04-22 12:06 UTC, arvinxx approved these changes

2024-04-22 12:14 UTC, merged