🔨 chore: Optimized MaxToken Slider
lobehub/lobehub pull request #2258
Opened 2024-04-28 08:05 UTC by sxjeru

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [x] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

1k -> 0（无限制），200k -> 256k（避免重叠），k -> K。
限制最小值为 0，step 跨度从 1k 改为 2k 。
1k = 1000 -> 1k = 1024.

稍等尝试适配 i18n 。
移动端测试刻度依旧重叠，需要适配去掉单位，本人暂不考虑。

#### 📝 补充信息 | Additional Information
old：
![image](https://github.com/lobehub/lobe-chat/assets/20513115/4b8f1c56-bef8-4dfa-b4bb-9cd45d2d6583)

new：
![image](https://github.com/lobehub/lobe-chat/assets/20513115/dee7c6bd-0fbc-4d3e-86fc-34cbecaebe05)

2024-04-28 09:03 UTC, arvinxx commented
256k 不太合理，目前主流的都是200k

2024-04-28 09:15 UTC, sxjeru commented
256k 可能不够实用。

如果输入自定义模型 id，能自动从 lobechat 模型库中取到 tokens 值，想必能取代不少 200k 场景。

2024-04-28 09:55 UTC, arvinxx commented
> 如果输入自定义模型 id，能自动从 lobechat 模型库中取到 tokens 值，想必能取代不少 200k 场景。


@sxjeru 我觉得这个倒是挺合理的，如果支持了这个，再把 200k 换成 256k 就没太大问题。

2024-04-28 11:48 UTC, sxjeru commented
commit 反馈。（上旧下新）

![image](https://github.com/lobehub/lobe-chat/assets/20513115/9cfa1f0d-104b-4153-b221-2c058c4ed4f1)
![image](https://github.com/lobehub/lobe-chat/assets/20513115/39a892e5-6f77-4fc3-ac1c-8b1d1e53c268)

---

如果保留200k，是不是考虑去掉128k的轴标签。（保留刻度点）
![image](https://github.com/lobehub/lobe-chat/assets/20513115/67559503-7453-4671-9a80-ee2ca98b102c)

2024-04-29 03:30 UTC, arvinxx commented
如果 0 是无限的话，我建议 token 的字符示意就应该也要用 无限大，而不是 Inf

> 如果保留200k，是不是考虑去掉128k的轴标签。（保留刻度点）

这个倒可以


> 这边还设想减小滑块的步长，从 仅刻度 细分到 1k 颗粒度，不知有无必要，是否会影响交互。

不需要减小。原因是 model 的 token 设定的最佳实践是 2 次幂。一般常见的都是 4k、8k、16k、32k 等等。不太会有奇怪脑回路的7k 、15k 这种。如果真存在的话，让右边自己输入就行。主流操作上还是通过刻度保证配置流畅性

2024-04-29 06:12 UTC, sxjeru commented
> 如果 0 是无限的话，我建议 token 的字符示意就应该也要用 无限大，而不是 Inf

这样可能导致其他语言的 tag 会很长，与 1K、1M 不太搭配。

---

此外还存在 k 到底指 1024 还是 1000 的问题，按国外某些惯例：1 kilo = 1k = 1000,
1 Kibi = 1K = 1024
对于当下**流行**模型，32K 及以下为 1024，128k 及以上为 1000，Gemini 的 1M 又是 1024*1024 。

目前处理方案 ff17c88 是 [128000, 1M) 采用 1000（小写 k），其他为 1024（大写 K），往后因时而变。
不知是否合适，还是至少统一 K 的大小写。（毕竟区分大小写也没几个人明白意思）

![image](https://github.com/lobehub/lobe-chat/assets/20513115/2ea842c2-cc90-4e55-8601-4c957a3d0c4e)

2024-04-29 08:23 UTC, arvinxx commented
> 这样可能导致其他语言的 tag 会很长 

我的意思使用 ∞ 这个符号

2024-04-29 16:28 UTC, arvinxx commented
@sxjeru 需要 rebase 下 main 了

2024-04-30 14:00 UTC, arvinxx requested changes
个别地方需要调整下~

2024-04-30 14:00 UTC, arvinxx commented on next.config.mjs
> +  images: {
这个不应该加

2024-04-30 14:00 UTC, arvinxx commented on src/components/ModelSelect/index.tsx
> +            <div className={cx(styles.tag, styles.tagBlue)} style={{ cursor: 'pointer' }} title="">
这里不应该加 pointer 。 pointer 一般是点击才加，这个只是hover有 tooltip

2024-04-30 14:00 UTC, arvinxx commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
最好这里将 1024 抽一个常量出来，比如叫 kiloUnit

2024-04-30 15:28 UTC, sxjeru commented on next.config.mjs
> +  images: {
已删。之前调试手机端报错，便改了这里。

2024-04-30 15:42 UTC, sxjeru commented on src/components/ModelSelect/index.tsx
> +            <div className={cx(styles.tag, styles.tagBlue)} style={{ cursor: 'pointer' }} title="">
这边主要考虑统一行为，因为类似 16k 的 tag 也是 pointer。
并且即便指针样式不变，实际点击的效果也是存在的（选中模型），而不是普通指针常见的单击无效。

暂且将遗漏的 vision 也改了，后续可再讨论。

2024-04-30 15:52 UTC, sxjeru commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
1024 应该来说挺直观了，如果换成常量名字可能得用 [Kibi](https://en.wikipedia.org/wiki/Binary_prefix) 之类的，总觉得还是 1024 更符合普遍认知。

2024-05-02 15:03 UTC, arvinxx commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
1024 是直观的，主要是分散的地方有点太多了，感觉抽个常量出来比较好感知

2024-05-02 15:27 UTC, arvinxx commented on next.config.mjs
> +  images: {
那个报错的问题我应该已经修复掉了

2024-05-02 15:28 UTC, arvinxx commented on src/components/ModelSelect/index.tsx
> +            <div className={cx(styles.tag, styles.tagBlue)} style={{ cursor: 'pointer' }} title="">
哦 好的

2024-05-02 15:35 UTC, arvinxx commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
>  const marks: SliderSingleProps['marks'] = {
这里的判断需要调整下了，把这个 marks 收到组件里吧。


我会在这个 PR 里 https://github.com/lobehub/lobe-chat/pull/2214 提供一个判断是否是 mobile 的方法：

```ts
const isMobile = useServerConfigStore(serverConfigSelectors.isMobile);
```

这个 marks 记得用 useMemo 包下

2024-05-03 01:59 UTC, sxjeru commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
>  const marks: SliderSingleProps['marks'] = {
看到 pr 合并了，这边午后会开始改。

2024-05-04 06:18 UTC, sxjeru commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
>  const marks: SliderSingleProps['marks'] = {
改好了。 c2527ba 

不过在pc端控制台测试切换移动设备时，isMobile 的值不会改变，等刷新后才改变，不知是什么问题。

2024-05-05 15:14 UTC, arvinxx commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
>  const marks: SliderSingleProps['marks'] = {
> 不过在pc端控制台测试切换移动设备时，isMobile 的值不会改变，等刷新后才改变，不知是什么问题。

这个是符合预期的。 isMobile 的判断来自服务端，基于 UA 获取。直接在 PC 端控制台切换到移动端设备时，UA 并不会重新获取，因此自然不会变。但当你重新刷新后，基于新的 UA 得到的 `isMobile` 则是新的。

2024-05-05 15:23 UTC, arvinxx commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
> +          max={exponent(1024)}
max={exponent(Kibi)}

2024-05-05 15:23 UTC, arvinxx commented on src/app/(main)/settings/llm/components/ProviderModelList/MaxTokenSlider.tsx
> +          step={2048}
2 * Kibi

2024-05-05 15:59 UTC, sxjeru commented
tag 里的 ∞ 比例感觉还是小了。
![image](https://github.com/lobehub/lobe-chat/assets/20513115/0a390f74-5d9d-4acf-a49c-26403386efc4)

2024-05-05 16:44 UTC, arvinxx commented
> tag 里的 ∞ 比例感觉还是小了。

是的…或者换成 icon 呢？ https://lucide.dev/icons/infinity

2024-05-06 10:32 UTC, sxjeru commented
icon 可行，希望调的还算适合。
![image](https://github.com/lobehub/lobe-chat/assets/20513115/5900459f-a2ad-486f-bb1c-0cda254af02e)

2024-05-08 03:23 UTC, arvinxx approved these changes
LGTM now, Thanks for your patience and great work!

2024-05-08 03:23 UTC, merged