♻️ refactor: Refactor Chat Layout
lobehub/lobehub pull request #2339
Opened 2024-05-02 03:29 UTC by canisminor1990

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [x] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

#### 📝 补充信息 | Additional Information

2024-05-02 03:42 UTC, arvinxx commented
把重构拆细，既然只重构 Chat Layout ，不能包含其他不相关的部分

2024-05-02 11:39 UTC, canisminor1990 commented
> 把重构拆细，既然只重构 Chat Layout ，不能包含其他不相关的部分

done

2024-05-03 04:27 UTC, arvinxx commented
ci 挂了

2024-05-03 04:45 UTC, arvinxx commented
不是说先不抽成这样么？只有一个children， topic 和 conversation 合成一个 page。

<img width="256" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/f6b0e6d9-f8de-49d4-ba7a-017296ee6d83">

`/chat/(chat)` 看着太复杂了

2024-05-03 08:30 UTC, canisminor1990 commented
> 不是说先不抽成这样么？应该只有一个 children， topic 和 conversation 合成一个 page。
> 
> <img width="256" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/f6b0e6d9-f8de-49d4-ba7a-017296ee6d83">
> 
> `/chat/(chat)` 看着太复杂了

我试了 只有抽出来 切session才不会闪

2024-05-03 08:36 UTC, canisminor1990 commented
> @canisminor1990 那之前说的新的布局要怎么解？

@conversation （布局一）
@flow （布局二）

这一层的 layout 可以控制切换哪个布局

2024-05-03 08:38 UTC, arvinxx commented
discord 那种「子区」呢？

2024-05-03 08:40 UTC, canisminor1990 commented
看定义 如果是新的布局则 单独见 @newlayout 如果是之前的某一种变体 则直接再 @对应的layout 中实现

2024-05-03 08:59 UTC, canisminor1990 commented
> What about discord’s “subsections”?


看定义 如果是新的布局则 单独见 @newlayout 如果是之前的某一种变体 则直接再 @对应的layout 中实现

2024-05-03 09:00 UTC, arvinxx commented
考虑下这两种：

1. Discord 的子区

<img width="1190" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/f4447eae-2209-47b1-b398-e6ec8bd34ebe">

2. 多面板布局

<img width="1512" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e1a5fd47-ebf3-4794-bfcd-37e8aef90927">

如果都要支持的话，要怎么弄

2024-05-03 09:49 UTC, canisminor1990 commented
> 考虑下这两种：
> 
> 1. Discord 的子区
> 
> <img width="1190" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/f4447eae-2209-47b1-b398-e6ec8bd34ebe">
> 
> 2. 多面板布局
> 
> <img width="1512" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e1a5fd47-ebf3-4794-bfcd-37e8aef90927">
> 
> 如果都要支持的话，要怎么弄

这种直接在@convetsation里做 现在里面是引用了一个完整的组件，多面板相当于加个map

2024-05-04 16:17 UTC, arvinxx commented on src/features/Conversation/components/SkeletonList.tsx
> +  right: css`
不应该叫 `right` 吧，RTL 的怎么办？用 use 、assistant 这样命名更加易于理解

2024-05-04 16:17 UTC, arvinxx commented on src/features/Conversation/components/VirtualizedList/index.tsx
> +        itemContent={(index, id) => <ItemContent id={id} index={index} mobile={mobile} />}
这里不能这么写。 `(index, id) => <ItemContent id={id} index={index} mobile={mobile} />` 这样意味着每次都会创建一个新的匿名函数，导致 `itemContent` 这个 props 在每个渲染周期里都是新的，然后就会触发重复渲染。得改回来

2024-05-04 16:17 UTC, arvinxx commented on src/app/(main)/chat/@session/features/SessionListContent/index.tsx
> -SessionListContent.displayName = 'SessionListContent';
这个为啥给删了

2024-05-04 16:17 UTC, arvinxx commented on src/app/(main)/chat/@session/features/SessionListContent/List/index.tsx
> -  const { showCreateSession } = useServerConfigStore(featureFlagsSelectors);
为啥删了这个？不应该删掉的吧

2024-05-04 16:17 UTC, arvinxx commented on src/app/(main)/chat/@session/features/SessionListContent/DefaultMode.tsx
> -const SessionDefaultMode = memo(() => {
这个为啥又改成了 SessionListContent

2024-05-04 16:17 UTC, arvinxx commented on src/app/(main)/chat/settings/_layout/Mobile/Header.tsx
> +      onBackClick={() => router.back()}
用 back 始终不对的，如果用户直接打开的是 `/chat/settings` 点返回就直接回到空白页而不是 chat 页

2024-05-04 16:17 UTC, arvinxx commented on src/hooks/useInterceptingRoutes.ts
这个改的目的是啥？

2024-05-04 16:17 UTC, arvinxx commented on src/features/SyncStatusInspector/DisableSync.tsx
我建议 SyncStatusinspector 不要改了，不属于此次 PR 的范畴之内。

2024-05-04 16:17 UTC, arvinxx commented on src/features/User/UserAvatar.tsx
> +        style={{ flex: 'none', ...style }}
这个的目的是啥？

2024-05-04 16:47 UTC, arvinxx requested changes

2024-05-04 16:47 UTC, arvinxx commented on src/app/(main)/chat/(workspace)/@topic/features/SystemRole/SystemRoleContent.tsx
> -  const openChatSettings = useOpenChatSettings(ChatSettingsTabs.Prompt);
我感觉 `openChatSettings` 的变动应该单独起一个 PR 先做，有点影响这个 PR 的内容了。

2024-05-04 16:47 UTC, arvinxx commented on src/features/FolderPanel/index.tsx
> +    handleExpand(md);
这里这么改会有问题的，当用户把左侧面板关闭以后刷新页面，第一次是会渲染到关闭状态OK的。但是当用户再次刷新页面，此时就会切到开启状态，而不是维持在关闭状态。

2024-05-04 16:47 UTC, arvinxx commented on src/features/Conversation/components/VirtualizedList/ItemContent.tsx
改回来的话，这个文件就删掉吧

2024-05-04 16:47 UTC, arvinxx commented on src/app/(main)/chat/@session/default.tsx
> +      <Migration>
这里感觉存在一个风险点？如果用户直接进到的是不含 `@session` 的页面（例如 mobile 下的 /chat 或者 /chat/settings）， Migration 就不会触发。

2024-05-04 16:47 UTC, arvinxx commented on src/app/(main)/chat/(workspace)/features/ShareButton/Preview.tsx
整个 ShareButton 重复了？是 `chat/features` 里的没删掉？

2024-05-04 16:48 UTC, arvinxx commented on src/app/(main)/chat/@session/features/SessionHydration.tsx
这个也是重复的没删掉

2024-05-04 16:53 UTC, arvinxx commented on src/app/(main)/chat/(workspace)/@topic/features/SidebarHeader.tsx
`@/components/SidebarHeader.tsx` 里有，为啥这边重复引入？应该要删一个

2024-05-04 16:53 UTC, arvinxx commented on src/app/(main)/chat/(workspace)/@topic/features/TopicListContent/Topic/DefaultContent.tsx
整个 TopicListContent 都是和 `/chat/features` 里的重复的，要看下是否删掉原来的

2024-05-06 03:08 UTC, canisminor1990 commented on src/hooks/useInterceptingRoutes.ts
参数放在下面传入更合理，放在 use 里不好，比如 openSettings 想打开几个不同页面

2024-05-06 03:09 UTC, canisminor1990 commented on src/features/User/UserAvatar.tsx
> +        style={{ flex: 'none', ...style }}
在 flex 边界情况下防止 avatar 被挤压变形

2024-05-06 05:39 UTC, arvinxx commented on src/app/(main)/chat/(workspace)/features/PluginTag/PluginStatus.tsx
这个也只要挪下？

2024-05-06 05:39 UTC, arvinxx commented on src/features/Conversation/components/VirtualizedList/index.tsx
> +import Item from '@/features/Conversation/components/ChatItem';
导入换成相对导入

2024-05-06 05:45 UTC, arvinxx commented on src/app/(main)/chat/@session/features/SessionHydration.tsx
> +  const mobile = useServerConfigStore((s) => s.isMobile);
这个不应该改的吧？ 本来一开始的意图就是想把 isMobile 这个动态值注入到 sessionStore 里的。

2024-05-06 05:45 UTC, arvinxx commented on src/app/(main)/chat/features/SettingButton.tsx
为啥这个是删掉了？没有移动么？

2024-05-06 05:46 UTC, canisminor1990 commented on src/app/(main)/chat/features/SettingButton.tsx
已经挪进去了

2024-05-06 07:33 UTC, arvinxx commented on src/app/(main)/chat/@session/features/SessionHydration.tsx
> +  // TODO: 后面考虑可以删除了，用 useServerConfigStore 就不需要再这里注入了
我记得之前在 seesion 里用 isMobile 的原因是为了做路由的跳转判断，如果现在能都收到 /chat 里，这个可能的确是不需要了的

2024-05-06 11:13 UTC, arvinxx commented
@canisminor1990 有冲突？

2024-05-07 02:22 UTC, canisminor1990 commented
> @canisminor1990 有冲突？

好了

2024-05-07 02:50 UTC, arvinxx commented
测试挂了

2024-05-07 04:55 UTC, canisminor1990 commented
> 测试挂了

好了

2024-05-08 12:41 UTC, arvinxx approved these changes

2024-05-08 12:43 UTC, merged