✨ feat: Add Settings Intercepting Routes
lobehub/lobehub pull request #2346
Opened 2024-05-02 08:56 UTC by canisminor1990

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

#### 📝 补充信息 | Additional Information

2024-05-02 14:17 UTC, arvinxx reviewed
看完了，我再测下功能

2024-05-02 14:17 UTC, arvinxx commented on src/app/(main)/chat/(desktop)/features/SideBar/SystemRole/index.tsx
我在想我们后面应该要改下 Sidebar 这个命名了，之前到处都是 Sidebar … 比如就叫 Inspector 这种，专门开一个 PR 来改

2024-05-02 14:17 UTC, arvinxx commented on src/app/(main)/chat/features/SettingButton.tsx
> +      onClick={openChatSettings}
这个似乎没有处理 `inbox` 的逻辑？

2024-05-02 14:17 UTC, arvinxx commented on src/app/(main)/chat/settings/modal/page.tsx
> +
这里加个 RFC 的链接，到时候方便跳过去看: 

```ts
// refs:  https://github.com/lobehub/lobe-chat/discussions/2295#discussioncomment-9290942
```

2024-05-02 14:17 UTC, arvinxx commented on src/app/(main)/settings/modal/page.tsx
同样加一下 rfc 链接~

2024-05-02 14:17 UTC, arvinxx commented on src/app/@modal/(.)settings/modal/index.tsx
> +const About = dynamic(() => import('@/app/(main)/settings/about'), { loading });
感觉如果是 modal 是独立 route 的话可能就不用 ssr 了？是不是可以加 `ssr:false` 了？

2024-05-02 14:17 UTC, arvinxx commented on src/app/@modal/(.)settings/modal/layout.tsx
> +const UpgradeAlert = dynamic(() => import('@/app/(main)/settings/features/UpgradeAlert'), {});
后面没东西的话， `{}` 可以不要？

2024-05-02 14:17 UTC, arvinxx commented on src/app/@modal/_layout/SettingModalLayout.tsx
> +import Header from '@/app/(main)/settings/_layout/Desktop/Header';
这个导入略难受，但是不是目前没法解？

2024-05-02 14:17 UTC, arvinxx commented on src/app/@modal/chat/(.)settings/modal/layout.tsx
> +import { Provider, createStore } from '@/features/AgentSetting/store';
这里也是，不太明白为何需要把 AgentSetting 打散再组装？

2024-05-02 14:17 UTC, arvinxx commented on src/app/@modal/chat/(.)settings/modal/page.tsx
> +const AgentChat = dynamic(() => import('@/features/AgentSetting/AgentChat'), { loading });
加 ssr:false

2024-05-02 14:17 UTC, arvinxx commented on src/hooks/useInterceptingRoutes.ts
这个补个单测吧

2024-05-02 14:25 UTC, arvinxx commented
复现方式：开一个自定义助手，然后打开设置

https://github.com/lobehub/lobe-chat/assets/28616219/9dd3f8df-8e30-449d-89ee-2c5f534453f0

2024-05-02 14:26 UTC, arvinxx commented
需要加间距

<img width="1134" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/7e30511b-901e-4570-940d-e1081419d925">

2024-05-02 14:28 UTC, arvinxx commented
截图后就自动关闭了（按了回车键），然后此时就打不开了 ：


https://github.com/lobehub/lobe-chat/assets/28616219/8727e151-26f2-4e06-814f-8b4c234421d4

2024-05-02 15:18 UTC, canisminor1990 commented on src/app/(main)/chat/features/SettingButton.tsx
> +      onClick={openChatSettings}
处理了 上面   const openChatSettings = useOpenChatSettings(isInbox);

2024-05-02 15:23 UTC, canisminor1990 commented on src/app/@modal/_layout/SettingModalLayout.tsx
> +import Header from '@/app/(main)/settings/_layout/Desktop/Header';
暂时没有

2024-05-02 15:24 UTC, canisminor1990 commented on src/app/@modal/chat/(.)settings/modal/layout.tsx
> +import { Provider, createStore } from '@/features/AgentSetting/store';
这边得拆开，因为是分页的

2024-05-02 15:49 UTC, canisminor1990 commented
> 截图后就自动关闭了（按了回车键）：
这是个 antd 的 triggle 吧？

2024-05-02 16:15 UTC, canisminor1990 commented
@arvinxx done

2024-05-03 01:32 UTC, arvinxx commented on src/app/(main)/settings/modal/page.tsx
这为啥不直接用 服务端的 redirect，要用客户端的？

2024-05-03 01:32 UTC, arvinxx commented on src/app/(main)/settings/llm/index.tsx
这里咋又改了

2024-05-03 02:34 UTC, canisminor1990 commented on src/app/(main)/settings/modal/page.tsx
要解析 query 才能去对应的页面

2024-05-03 02:34 UTC, canisminor1990 commented on src/app/(main)/settings/llm/index.tsx
应该是 merge 的时候回去了

2024-05-03 03:01 UTC, arvinxx commented on src/app/(main)/settings/modal/page.tsx
我记得 query 在服务端也能读到的呀

2024-05-03 09:01 UTC, canisminor1990 commented on src/app/(main)/settings/modal/page.tsx
改了

2024-05-04 02:27 UTC, arvinxx requested changes

2024-05-04 02:27 UTC, arvinxx commented on src/app/(main)/settings/modal/page.tsx
> +  return redirect(urlJoin('/settings', searchParams.tab));
我发现还是不能用 server redirect … 线上会抛错… 得改回 client 的…

<img width="1574" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/6aa3879f-6eae-4cac-bba3-923c1ccda0f0">

2024-05-04 06:04 UTC, canisminor1990 commented
![image](https://github.com/lobehub/lobe-chat/assets/17870709/88317621-607a-4361-b394-5db21aec295c)

2024-05-04 06:09 UTC, merged