🐛 fix: Azure OpenAI Vision models issue
lobehub/lobehub pull request #2429
Opened 2024-05-08 07:16 UTC by AnoyiX

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Fixed an issue where the server side was abnormal when using the Vision model in Azure OpenAI.

修复 Azure OpenAI 在使用 Vision 模型时，服务端异常的问题。

- fix #2207 
- fix #2375
- fix #2045
- fix #1778

#### 📝 补充信息 | Additional Information

在使用 Vision 模型时，如果用户上传图片，那么 Messages 中会存在 type 为 `image_url` 的内容，示例如下：

```json
{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "Describe this picture:"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "<image URL>"
          }
        }
      ]
    }
  ]
}
```

然而，官方的 SDK `@azure/openai` 在序列化 Message 时，用的 `imageUrl` 这个键值，从而导致报错 ISSUE [https://github.com/lobehub/lobe-chat/issues/2207](https://github.com/lobehub/lobe-chat/issues/2207)

官方 SDK 源码：`node_modules/@azure/openai/dist/index.cjs` 中的函数 `serializeChatMessageImageContentItem`

```javascript
/** serialize function for ChatMessageImageContentItem */
function serializeChatMessageImageContentItem(obj) {
    return {
        type: obj["type"],
        image_url: { url: obj.imageUrl["url"], detail: obj.imageUrl["detail"] },
    };
}
```

2024-05-08 09:46 UTC, AnoyiX commented
> 这个问题不算是 azure-openai 官方 SDK 的问题么？

也不能完全说是官方 SDK 的问题，官方的 SDK 中字段的定义基本都是驼峰格式的， 如果单独使用官方的 SDK 去测试，按官方的格式来，是没有问题的。现在 LobeChat 传的 messages 字段格式不转换成驼峰格式的话，就和官方不兼容。

2024-05-08 11:43 UTC, arvinxx requested changes

2024-05-08 11:43 UTC, arvinxx commented on src/libs/agent-runtime/azureOpenai/index.ts
> +    messages.forEach(message => {
请参考 https://github.com/lobehub/lobe-chat/blob/main/src/libs/agent-runtime/google/index.ts#L135-L172 这里，创建一个私有方法来做数据结构的转换，这样会干净一些。然后需要补充一下对应的数据结构转换的单元测试

2024-05-09 01:53 UTC, AnoyiX commented on src/libs/agent-runtime/azureOpenai/index.ts
> +    messages.forEach(message => {
嗯嗯

2024-05-10 03:58 UTC, AnoyiX commented
代码中，给 `maxTokens` 增加了一个默认值，是因为在默认情况下，使用 Azure 的 Vision 模型，如果不传 `max_tokens` 参数，AI 回复的内容不全，仅会响应少量文本，这里设置一个较大的默认值，就会接收到完整的 AI 回复。

这应该是 Azure 官方 API 的问题，这里给 `maxTokens` 增加了一个默认值仅仅是为了提升 LobeChat 的用户体验。

2024-05-10 06:54 UTC, arvinxx commented
> 这应该是 Azure 官方 API 的问题，这里给 maxTokens 增加了一个默认值仅仅是为了提升 LobeChat 的用户体验。

合理的 👍

2024-05-10 06:58 UTC, arvinxx commented
<img width="1230" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/d4a43d09-062a-409e-b46d-ea6dfc0a97c8">

@AnoyiX 跑下 lint 的 fix，构建没通过

2024-05-10 06:59 UTC, AnoyiX commented
> <img alt="image" width="1230" src="https://private-user-images.githubusercontent.com/28616219/329488226-d4a43d09-062a-409e-b46d-ea6dfc0a97c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjQ1OTcsIm5iZiI6MTcxNTMyNDI5NywicGF0aCI6Ii8yODYxNjIxOS8zMjk0ODgyMjYtZDRhNDNkMDktMDYyYS00MDllLWI0NmQtZWE2ZGZjMGE5N2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2NTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTkxOTcxNzZkZDQyMzBiYjRhZTgwMTE4NWU2MzgzYzM5N2VmZWYxZjBiNTJkNjAxNzI4ZmFlNTM5NGIwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OTlLSMKH30Ww-uawuoZmWYvzjI23m8AQqkx1S95xB9E">
> @AnoyiX 跑下 lint 的 fix，构建没通过

正在处理，等我几分钟

2024-05-10 07:35 UTC, merged