✨ feat: Add profile
lobehub/lobehub pull request #2433
Opened 2024-05-08 15:44 UTC by canisminor1990

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

#### 📝 补充信息 | Additional Information

2024-05-09 06:07 UTC, arvinxx requested changes

2024-05-09 06:07 UTC, arvinxx commented on locales/nl-NL/common.json
这里有中文，感觉要重新生成下

2024-05-09 06:07 UTC, arvinxx commented on src/features/User/UserLoginOrSignup.tsx
> -      <UserInfo />
我觉得要加个是匿名用户的提示的吧

<img width="362" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e617b0a4-e1e0-434c-a135-d5d0387b7c5f">

2024-05-09 06:07 UTC, arvinxx commented on src/features/User/UserPanel/useMenu.tsx
> +    ...(enableClerk && isLoginWithAuth ? profile : []),
不要单独写这种判断，如果需要 isLoginWithClerk，在 selectors 里加一个，这样其他地方也能复用，不然到时候这种逻辑很难维护的。

2024-05-09 06:07 UTC, arvinxx commented on src/features/User/UserPanel/useMenu.tsx
> +    ...(enableClerk && isLoginWithAuth ? profile : []),
我看前面一个地方也有用到这个判断

<img width="811" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/1c43ab93-ccd3-47ed-892c-60a04644a277">

2024-05-09 10:14 UTC, canisminor1990 commented
@arvinxx done

2024-05-13 04:50 UTC, canisminor1990 commented
@arvinxx

2024-05-13 06:19 UTC, arvinxx commented
Topic 的改动不要合在这个 PR 里，单独拆出去

2024-05-13 09:41 UTC, arvinxx approved these changes

2024-05-13 09:41 UTC, merged