✨ feat: Add PWA install button
lobehub/lobehub pull request #2438
Opened 2024-05-09 09:53 UTC by canisminor1990

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

#### 📝 补充信息 | Additional Information

2024-05-11 07:46 UTC, arvinxx requested changes
<img width="588" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/a9e5211f-b94f-48f7-a767-988191c01786">

这个 title 有点牛皮癣广告的感觉了，得改下

2024-05-11 07:46 UTC, arvinxx commented on public/manifest.json
> +  "description": "Personal LLM productivity tool, brings you the best user experience of ChatGPT, OLLaMA, Gemini, Claude WebUI. Engineer Assistant functionalities tailored to your private desires, ta
> Engineer Assistant functionalities tailored to your private desires, tackle challenges, boost productivity, and navigate the frontier of workflow in LobeChat

这半句没看懂

2024-05-11 07:46 UTC, arvinxx commented on src/app/metadata.ts
> +      creator: '@lobehub',
不要加 creator

2024-05-13 06:29 UTC, arvinxx commented on src/server/ld.ts
> +    // TODO: 需要新增一个 updateAt
这个 TODO 是啥用的？

2024-05-13 06:29 UTC, arvinxx commented on src/app/metadata.ts
> +    alternates: { canonical: getCanonicalUrl('/') },
这个不能写在这里。layout 会影响所有页面。 canonical 只应该放在 page，而不是 layout 里

2024-05-13 06:29 UTC, arvinxx commented on src/server/ld.ts
> +    avatar: 'https://hub-apac-1.lobeobjects.space/landing/avatar/lobe-hub.webp',
不要用这个 CDN，其他私有化部署的站点会跨域的，要么放到 public去，要么用 github 的地址吧

2024-05-13 08:59 UTC, arvinxx requested changes
<img width="850" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/ebcf8d8c-21e4-44dc-a921-3de0aafdcdd4">

切换设置tab，标题并不会跟随修改

2024-05-13 08:59 UTC, arvinxx commented on locales/nl-NL/plugin.json
翻译不对

2024-05-13 08:59 UTC, arvinxx commented on locales/pl-PL/plugin.json
翻译不对

2024-05-13 08:59 UTC, arvinxx commented on src/app/page.tsx
> -  alternates: { canonical: getCanonicalUrl('/') },
这个不能删

2024-05-13 11:58 UTC, canisminor1990 commented
@arvinxx done

2024-05-13 12:36 UTC, arvinxx approved these changes

2024-05-13 12:36 UTC, merged