💄 style: Fix scroll and expand
lobehub/lobehub pull request #2470
Opened 2024-05-13 06:28 UTC by canisminor1990

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

修复侧边栏小屏展开需要点两侧，修复桌面端 overflow

#### 📝 补充信息 | Additional Information

2024-05-13 09:07 UTC, arvinxx requested changes

2024-05-13 09:07 UTC, arvinxx commented on src/features/Conversation/components/InboxWelcome/AgentsSuggest.tsx
> +          : agentList.slice(sliceStart, sliceStart + agentLength).map((agent) => (
这个为啥改

2024-05-13 09:07 UTC, arvinxx commented on src/app/(main)/chat/@session/_layout/Desktop/SessionHeader.tsx
> +  const { desktop = true } = useResponsive();
这个没用的，12寸 的 iPad 尺寸也是 desktop，你这样会导致 12寸 iPad 上还是不显示按钮。

先改回来，让之前提 PR 的人来搞。

2024-05-13 09:07 UTC, arvinxx commented on src/app/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Main.tsx
一样，先改回来

2024-05-13 09:09 UTC, arvinxx commented
<img width="385" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/07c387a9-2433-4bdf-933c-7302678f95ee">

2024-05-13 11:59 UTC, canisminor1990 commented on src/features/Conversation/components/InboxWelcome/AgentsSuggest.tsx
> +          : agentList.slice(sliceStart, sliceStart + agentLength).map((agent) => (
不能用 useMemo 切主题有问题

2024-05-13 12:10 UTC, canisminor1990 commented
@arvinxx done

2024-05-14 12:32 UTC, arvinxx commented
@canisminor1990 rebase下main

2024-05-14 14:01 UTC, merged