💄 style: Modify bedrock provided model
lobehub/lobehub pull request #2473
Opened 2024-05-13 08:53 UTC by RubuJam

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change
修改bedrock提供的模型
Modify bedrock provided model

#### 📝 补充信息 | Additional Information

2024-05-14 05:27 UTC, arvinxx requested changes

2024-05-14 05:27 UTC, arvinxx commented on src/config/modelProviders/bedrock.ts
desc 不要拿掉

2024-05-14 05:27 UTC, arvinxx commented on src/config/modelProviders/bedrock.ts
> +      id: 'meta.llama3-70b-instruct-v1:0',
llama3 直接开启来没有用的，我之前试过了

2024-05-14 05:27 UTC, arvinxx commented on src/config/modelProviders/bedrock.ts
> +      id: 'mistral.mixtral-8x7b-instruct-v0:1',
mistral 的也是，没法直接开启来，需要额外在 bedrock 的 provider 实现 mistral 的调用逻辑

2024-05-14 05:27 UTC, arvinxx commented on src/config/modelProviders/groq.ts
这个不要改，llama3 应该是最顶上

2024-05-14 05:27 UTC, arvinxx commented on src/libs/agent-runtime/deepseek/index.test.ts
deepseek 的单独拆一个另外的pr出来

2024-05-14 08:01 UTC, arvinxx approved these changes

2024-05-14 08:02 UTC, arvinxx requested changes

2024-05-14 08:02 UTC, arvinxx commented on src/config/modelProviders/bedrock.ts
> +      enabled: true,
我感觉 titian 可能不应该默认 enabled，因为效果不好

2024-05-14 08:03 UTC, RubuJam commented on src/config/modelProviders/bedrock.ts
> +      enabled: true,
我马上修改一下

2024-05-14 08:07 UTC, RubuJam commented on src/config/modelProviders/bedrock.ts
> +      enabled: true,
修改好了

2024-05-14 11:33 UTC, arvinxx commented on src/app/(main)/settings/llm/Bedrock/index.tsx
> +      modelList={{ showModelFetcher: true }}
这个加了应该没用的吧？我没有给 bedrock 加 models 的方法哎

2024-05-14 11:43 UTC, RubuJam commented on src/app/(main)/settings/llm/Bedrock/index.tsx
> +      modelList={{ showModelFetcher: true }}
那我先注释掉

2024-05-14 15:11 UTC, RubuJam commented
@arvinxx 要不先把这个PR合并了，我后面加方法了另外再提一个PR？

Merge this PR first, and I'll add the method later and mention another PR?

2024-05-15 04:46 UTC, sxjeru commented on src/config/modelProviders/bedrock.ts
> -      tokens: 8000,
https://docs.aws.amazon.com/zh_cn/bedrock/latest/userguide/model-parameters-titan-text.html
https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-titan-models-express-lite-bedrock/
参考上面文档的 maxTokenCount，以及发布新闻，8K 应当为 8000，Lite 也应当为 4000.

2024-05-20 01:25 UTC, arvinxx commented on src/config/modelProviders/bedrock.ts
> -      tokens: 8000,
+1

2024-05-20 04:27 UTC, arvinxx approved these changes
LGTM~ Thanks!

2024-05-20 04:27 UTC, merged