:construction: wip: lobe nextauth db adapter
lobehub/lobehub pull request #2935
Opened 2024-06-19 08:58 UTC by cy948

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

##### 6/19/2024
> 参考 [drizzle db adapter](https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-drizzle/src/lib/pg.ts) 实现大部分操作

- 📦  `package.json`: 更新 authjs 和 authcore 版本；
- ✨ `src/database/server/models/nextauth/account.ts`: 定义 [Account DB 操作](https://authjs.dev/concepts/database-models#account)；
- ✨ `src/database/server/models/nextauth/authenticator.ts`: 定义 [AuthenticatorDB 操作](https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-drizzle/src/lib/pg.ts)；
- ✨ `src/database/server/models/nextauth/session.ts`:  定义 [Session Db 操作](https://authjs.dev/concepts/database-models#session)；

#### 📝 补充信息 | Additional Information

2024-06-25 09:18 UTC, cy948 commented on src/server/context.ts
> +      if (session && session?.user?.id) {
此处连带判断 `session.user.id` 是因为若 userId 为空，auth 不为空，会导致进入 `/` 时会无限 loading。卡在 `src/app/(loading)/Redirect.tsx:23` 。

2024-07-07 03:02 UTC, arvinxx commented
冲突解决下？

2024-07-07 03:11 UTC, arvinxx commented on src/database/server/migrations/0004_chunky_joseph.sql
给个语义化的名称 004_add_next_auth 这种

2024-07-07 03:11 UTC, arvinxx commented on src/server/context.ts
> +  auth?: ClerkAuth | User;
建议拆一下，这个 auth改名为 clerkAuth，然后再加一个 nextAuth

2024-07-07 03:11 UTC, arvinxx commented on src/app/(main)/(mobile)/me/(home)/features/UserBanner.tsx
> +    s.enableAuth(),
`s.enableAuth` 的写法和其他的调用太不统一了，能把这个变成 selectors 的调用模式么

2024-07-09 09:56 UTC, cy948 commented on src/database/server/migrations/0004_chunky_joseph.sql
更改这个文件的名字后，是不是还需要在 `src/database/server/migrations/meta/_journal.json` 中改咧？

2024-07-09 10:25 UTC, cy948 commented on src/app/(main)/(mobile)/me/(home)/features/UserBanner.tsx
> +    s.enableAuth(),
已全部改成 selector 的调用方式

2024-07-09 10:54 UTC, cy948 commented on src/server/context.ts
> +  auth?: ClerkAuth | User;
已拆分

2024-07-10 16:53 UTC, cy948 commented on src/database/server/migrations/0004_chunky_joseph.sql
已改为 `0004_add_next_auth.sql`，同时也更改了读取 migration sqls 的`_journal.json`。 https://github.com/lobehub/lobe-chat/pull/2935/commits/7758b764aa82e0681e3976792b24e99df8f6a432

2024-07-15 05:47 UTC, arvinxx commented
rebase 下

2024-07-15 09:21 UTC, cy948 commented
@arvinxx rebase完了，还在 `src/config/auth.ts` 加了些提示方便用户迁移环境变量。

2024-07-16 05:11 UTC, arvinxx requested changes

2024-07-16 05:11 UTC, arvinxx commented on src/database/server/migrations/meta/0000_snapshot.json
0~3 的snapshot 撤回下变更？感觉没必要

2024-07-16 05:11 UTC, arvinxx commented on src/database/server/schemas/lobechat.ts
> +  emailVerified: timestamptz('email_verified'),
`emailVerifiedAt: timestamptz('email_verified_at'),`

保持命名风格统一

2024-07-16 05:11 UTC, arvinxx commented on src/libs/next-auth/adapter/index.ts
这个文件看上去是 next-auth db 的核心逻辑模块，需要补充单测

2024-07-16 05:11 UTC, arvinxx commented on src/libs/next-auth/adapter/index.ts
> +    async createAuthenticator(authenticator) {
这里每个函数的类型需要显式声明下

2024-07-16 05:11 UTC, arvinxx commented on src/libs/next-auth/adapter/schema.ts
> +  `${LOBE_NEXTAUTH_TABLE_PREFIX}accounts`,
不需要提一个前缀变量，直接用 `nextauth_accounts` ，未来也不太可能去改个表名前缀的

2024-07-16 05:11 UTC, arvinxx commented on src/libs/next-auth/adapter/schema.ts
我有个问题，这个schema 有没有必要单独提到这个adapter里？是否直接写到 `lobechat.ts` 里更合适？

2024-07-16 05:11 UTC, arvinxx commented on src/server/context.ts
> +  auth?: ClerkAuth | User;
我的意思其实是auth 改成 clerkAuth ，然后再加一个 nextAuth 。而不是 auth 对象既可能是 clerkAuth ，也可能是 NextAuth

这个直接改应该问题不大。我印象里这个 auth 应该没有地方用到

2024-07-16 05:11 UTC, arvinxx commented on src/server/context.ts
> +  return createContextInner({ authorizationHeader: authorization });
userId 漏了

2024-07-16 05:17 UTC, arvinxx commented on src/app/api/auth/error/page.tsx
> +export default dynamic(() => import('@/components/NextAuth/AuthErrorPage'));
这个页面应该直接拿来过，不应该把 AuthErrorPage 放到 components 里

2024-07-16 05:17 UTC, arvinxx commented on src/app/(main)/settings/common/features/Theme/index.tsx
如果走左上角的登录了的话，这里的入口是不是应该就下掉了

2024-07-16 05:17 UTC, arvinxx commented on src/config/auth.ts
这个在 https://github.com/lobehub/lobe-chat/pull/2983/files#diff-7f65b132e71dbda336098bfe15b682f910d17c36f3cc29aa1ffeb07161eb30ea 已经删掉了，不应该再加回来。1.0 前就提示了，现在已经 1.0 了

2024-07-16 08:36 UTC, cy948 commented on src/app/api/auth/error/page.tsx
> +export default dynamic(() => import('@/components/NextAuth/AuthErrorPage'));
`AuthErrorPage` 直接放在`src/app/api/auth/error/`这个目录吗？

2024-07-16 09:15 UTC, cy948 commented on src/libs/next-auth/adapter/schema.ts
我一开始想的是分开放会方便管理一点。可以放到`lobechat.ts`吗？一共有 4 个表。

2024-07-16 09:21 UTC, cy948 commented on src/database/server/migrations/meta/0000_snapshot.json
已撤回

2024-07-16 09:22 UTC, cy948 commented on src/database/server/schemas/lobechat.ts
> +  emailVerified: timestamptz('email_verified'),
已改为上述命名。 https://github.com/lobehub/lobe-chat/pull/2935/commits/5ee2d9c623ba1d9c373a1625daf49cb0193a45eb

2024-07-16 09:23 UTC, arvinxx commented on src/app/api/auth/error/page.tsx
> +export default dynamic(() => import('@/components/NextAuth/AuthErrorPage'));
对

2024-07-16 09:24 UTC, cy948 commented on src/config/auth.ts
已去除提示 https://github.com/lobehub/lobe-chat/pull/2935/commits/00b06170ecbf4dcf1cf474649915a6506d03d583

2024-07-16 09:25 UTC, arvinxx commented on src/libs/next-auth/adapter/schema.ts
db 的 schema 最好合在一起管理。先和 lobechat.ts 放同一个目录吧，我后面做个改造，把 lobechat.ts 改成文件夹形式，然后拆几个子文件出来

2024-07-16 09:27 UTC, cy948 commented on src/server/context.ts
> +  return createContextInner({ authorizationHeader: authorization });
已补充 https://github.com/lobehub/lobe-chat/pull/2935/commits/5b45b5e89264b58cb249f2cde63988a179edc914

2024-07-16 09:28 UTC, cy948 commented on src/server/context.ts
> +  auth?: ClerkAuth | User;
现在拆开了：https://github.com/lobehub/lobe-chat/pull/2935/commits/5b45b5e89264b58cb249f2cde63988a179edc914

2024-07-16 09:29 UTC, cy948 commented on src/libs/next-auth/adapter/schema.ts
> +  `${LOBE_NEXTAUTH_TABLE_PREFIX}accounts`,
已去掉变量 https://github.com/lobehub/lobe-chat/pull/2935/commits/c2dea0f3ed8dd9ab0c57a26f58b34523b3dffbde

2024-07-16 09:56 UTC, cy948 commented on src/app/api/auth/error/page.tsx
> +export default dynamic(() => import('@/components/NextAuth/AuthErrorPage'));
已移动 https://github.com/lobehub/lobe-chat/pull/2935/commits/e30199c49ae0f27b28922f59558d7ce0e0ced239

2024-07-16 09:57 UTC, cy948 commented on src/libs/next-auth/adapter/schema.ts
移动到 lobechat.ts 的同一目录了 https://github.com/lobehub/lobe-chat/pull/2935/commits/f6953da3e602bede577d7c71cf8c73d08fce6a83

2024-07-16 11:09 UTC, cy948 commented on src/libs/next-auth/adapter/index.ts
> +    async createAuthenticator(authenticator) {
已显式声明 https://github.com/lobehub/lobe-chat/pull/2935/commits/38966ee2bfeb85f9736216fd3bf6ac3ca8d756e0

2024-07-17 06:16 UTC, arvinxx commented
其他我没啥问题了，就是要一个配置流程的文档，我跟着走一遍看看行不行

2024-07-17 06:47 UTC, cy948 commented
> 其他我没啥问题了，就是要一个配置流程的文档，我跟着走一遍看看行不行

OK，可以先在PR讨论区里补一个简单的配置文档吗？

2024-07-17 07:01 UTC, arvinxx commented
> > 其他我没啥问题了，就是要一个配置流程的文档，我跟着走一遍看看行不行
> 
> OK，可以先在PR讨论区里补一个简单的配置文档吗？

可以的

2024-07-18 01:25 UTC, Matinal111 commented
期待

2024-07-18 07:43 UTC, cy948 commented on src/app/(main)/settings/common/features/Theme/index.tsx
已下 https://github.com/lobehub/lobe-chat/pull/2935/commits/bbafe25f98b2a523a49b830582e2db1cef3b52fe

2024-07-18 07:45 UTC, cy948 commented on src/libs/next-auth/adapter/index.ts
补在了 `src/database/server/models/__tests__/nextauth.test.ts`，可以随 `pnpm test-server` 运行

2024-07-22 04:00 UTC, arvinxx commented
进到首页会抛错

<img width="1867" alt="image" src="https://github.com/user-attachments/assets/08f9cfee-0d71-4ea4-a0a8-86c172aaeae9">

2024-07-22 04:07 UTC, arvinxx commented
点击 signin Auth0 ，也仍然抛错：

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/d055443c-bf36-49ef-8a11-4cfa4eac4c62">

环境变量：

```env

NEXT_AUTH_SECRET=212b5de1a85c2bdb9cb461d8fac03a50
NEXT_AUTH_SSO_PROVIDERS=auth0
ACCESS_CODE=abc213ej2rl23

# Auth0 configurations
AUTH0_CLIENT_ID=xxx
AUTH0_CLIENT_SECRET=cSX_xxx
AUTH0_ISSUER=http://localhost:3010

NEXT_PUBLIC_SERVICE_MODE=server
KEY_VAULTS_SECRET=
DATABASE_DRIVER=node
DATABASE_URL="postgresql://xxx:xxx@sha1.clusters.zeabur.com:30158/zeabur"
```

服务端错误日志：

```
[auth][error] OperationProcessingError: "response" is not a conform Authorization Server Metadata response
    at Module.processDiscoveryResponse (webpack-internal:///(rsc)/./node_modules/.pnpm/oauth4webapi@2.11.1/node_modules/oauth4webapi/build/index.js:289:15)
    at getAuthorizationUrl (webpack-internal:///(rsc)/./node_modules/.pnpm/@auth+core@0.28.0/node_modules/@auth/core/lib/actions/signin/authorization-url.js:25:68)

 POST /api/auth/signin/auth0 302 in 409ms

digest: "284795093"
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
```

2024-07-22 04:10 UTC, cy948 commented
@arvinxx 环境变量的 auth0 issuer 不太对，应该是这样的 https://lobehub.com/zh/docs/self-hosting/advanced/sso-providers/auth0#%E9%85%8D%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

2024-07-22 06:23 UTC, arvinxx commented
@cy948 在存在 clerk auth 用户数据的 db 中，用相同邮箱创建的账号并不会合并为一条。并且第二次重新点击登录时会抛错



<img width="1709" alt="image" src="https://github.com/user-attachments/assets/f3b3fe6c-888e-498b-990b-dd85e3109a3a">

<img width="803" alt="image" src="https://github.com/user-attachments/assets/3b48a997-d971-415e-86ce-93cd763bc8d8">

2024-07-22 17:44 UTC, cy948 commented
@arvinxx 现在能在登录的时候根据`email`自动关联存在用户了😋 https://github.com/lobehub/lobe-chat/pull/2935/commits/85f287f6ada925591fd1de476bc54bfefb53aa25

2024-07-25 14:05 UTC, cy948 commented
@arvinxx 因为 Github 没授权用户的 email，所以没有合并账户

2024-07-26 01:22 UTC, morningtzh commented
> @arvinxx 因为 Github 没授权用户的 email，所以没有合并账户。应该是和这个 provider 的 oauth scope 有关。

使用 auth0 的这种方式看上去可以直接关联账户，而不仅是通过email匹配
https://auth0.com/docs/manage-users/user-accounts/user-account-linking#advantages-of-linking-accounts

2024-07-26 03:17 UTC, cy948 commented
@morningtzh 这种方式很不错，但目前 nextauth 的 account linking 是自动处理的，没提供 ui 接入，以后可以通过 profile 页面实现。

2024-07-30 15:42 UTC, ykangw commented
感谢开发者的贡献！请问这次更新何时可以发布？NextAuth 的 Microsoft Entra ID  SSO 登陆已经超过1个月不能使用了，期待尽快修复。

2024-08-02 11:47 UTC, arvinxx approved these changes
LGTM now. Let's move forward.

2024-08-02 11:48 UTC, merged

2024-08-03 06:21 UTC, 534002646 commented
> LGTM now. Let's move forward.

![image](https://github.com/user-attachments/assets/e2e4b956-ae9d-4096-8c05-b64dae76d273)
报错信息："Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details."
我之前就是github登录，docker更新到最新版本1.8后，打开显示的是正常登陆状态，退出登陆后再次通过github登陆会报错，提示环境变量不正确，我确认环境变量跟之前相同

2024-08-03 11:37 UTC, cy948 commented
@534002646 docker有两个镜像，有一个是server版本，遇到问题的是哪个？

2024-08-03 11:40 UTC, 534002646 commented
> @534002646 docker有两个镜像，有一个是server版本，遇到问题的是哪个？

没有问题了，重新拉了数据库版本的，感谢🙏