✨ feat: Support Cloudflare Workers AI
lobehub/lobehub pull request #2966
Opened 2024-06-21 08:57 UTC by sxjeru

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

参考 #2804 完成，目前已可对话，剩余事项如下：

- [ ] 补全模型；
- [ ] 支持在设置中修改 Account id，而不是直接从 env 获得。

#### 📝 补充信息 | Additional Information

// ref https://developers.cloudflare.com/workers-ai/models/#text-generation
// api https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility

2024-06-21 10:28 UTC, arvinxx commented
Rebase下main

2024-06-21 10:30 UTC, arvinxx commented on src/config/llm.ts
> +      ENABLED_CF: z.boolean(),
官方的是缩写吗？如果不是的话我建议写完整，可读性比字少重要

2024-06-21 10:30 UTC, arvinxx commented on src/libs/agent-runtime/cloudflare/index.ts
> +//   chatCompletion: {
注释没用的话就删除掉吧

2024-06-21 10:52 UTC, sxjeru commented on src/config/llm.ts
> +      ENABLED_CF: z.boolean(),
改回全称了。

2024-06-21 11:19 UTC, arvinxx commented
有不少删了之前代码的地方。要revert回来

2024-06-21 11:37 UTC, arvinxx commented on src/config/modelProviders/cloudflare.ts
> +      displayName: 'LLaMA2-7B-chat',
为啥不用llama3的呢？

2024-06-21 11:37 UTC, arvinxx commented on src/libs/agent-runtime/cloudflare/index.ts
> +  baseURL: `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/ai/v1`,
这里要用 `llmEnv.XXX`

2024-06-21 13:41 UTC, sxjeru commented on src/libs/agent-runtime/cloudflare/index.ts
> +  baseURL: `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/ai/v1`,
换成 llmEnv.CLOUDFLARE_ACCOUNT_ID 之后报下述错误：
`Error: ❌ Attempted to access a server-side environment variable on the client

请教一下有什么办法能让设置页的 Cloudflare Account ID 同步到此处 baseURL？
配置项写在 src/app/api/chat/agentRuntime.ts 
```
case ModelProvider.Cloudflare: {
      const { CLOUDFLARE_API_KEY, CLOUDFLARE_ACCOUNT_ID } = getLLMConfig();
      const apiKey = apiKeyManager.pick(payload?.apiKey || CLOUDFLARE_API_KEY);
      const accountID = payload.apiKey && payload.cloudflareAccountID ? payload.cloudflareAccountID : CLOUDFLARE_ACCOUNT_ID;
      return { accountID, apiKey };
```

2024-07-01 09:42 UTC, arvinxx commented on src/libs/agent-runtime/cloudflare/index.ts
> +  baseURL: `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/ai/v1`,
accountId 作为参数传给 server端。然后 server 端的 LobeCloudflareAI 初始化时候 baseURL 的逻辑变成 accountId 拼接的？

2024-07-01 09:45 UTC, arvinxx commented on src/libs/agent-runtime/AgentRuntime.ts
> +        runtimeModel = new LobeCloudflareAI(params.cloudflare ?? {});
考虑下在这里做 accountId 的拼接传入。或者在 `LobeOpenAICompatibleFactory` 方法中加个 baseURL 允许是个入参函数的方法

2024-07-01 14:14 UTC, arvinxx requested changes

2024-07-01 14:14 UTC, arvinxx commented on src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
这个逻辑不对，params 不应该是 `cfAccountID`，params 应该是一个入参的泛型，然后返回是 string

const finalBaseURL = typeof baseURL === 'function' ? baseURL(params) : baseURL;

2024-07-01 14:33 UTC, sxjeru commented on src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
这边还是在 src/libs/agent-runtime/AgentRuntime.ts 实现拼接好了，技术力不太够。

2024-07-09 13:07 UTC, arvinxx commented
得 reabse 下

2024-08-05 02:34 UTC, sxjeru commented
@BrandonStudio If you have free time, please do it.

`能者多劳`

2024-08-05 11:32 UTC, closed without merging