💄 style(ui): Confirmation when `adding a new topic`
lobehub/lobehub pull request #3030
Opened 2024-06-25 07:24 UTC by RubuJam

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change
在移动端点击`将当前会话保存为话题`时，会进行弹窗进行二次确认，避免误触

Upon selecting the option to "Save current conversation as topic" on the mobile terminal, a pop-up window will be displayed for secondary confirmation, thus preventing any potential accidental touches.

#### 📝 补充信息 | Additional Information
![photo](https://github.com/lobehub/lobe-chat/assets/36145660/07405e43-d1ee-4696-9d36-ff58ea0d2de7)

2024-06-25 13:28 UTC, RubuJam commented
@arvinxx Please review

2024-07-01 09:39 UTC, arvinxx requested changes

2024-07-01 09:39 UTC, arvinxx commented on src/features/ChatInput/Topic/index.tsx
> +      <Popconfirm
Mobile 上不要用 Popconfirm 吧，这个有点太小了。换成 `Modal .confirm` 好一些。另外逻辑写在 onClick 里，不建议再单独提一个 组件 Render 出来

2024-07-01 10:45 UTC, RubuJam commented on src/features/ChatInput/Topic/index.tsx
> +      <Popconfirm
Mobile上的`即将清空当前会话消息，清空后将无法找回，请确认你的操作`也是用的`Popconfirm`，实际效果也还可以，我感觉换不换都可以，如果需要，那我就换一下

2024-07-01 15:46 UTC, RubuJam commented on src/features/ChatInput/Topic/index.tsx
> +      <Popconfirm
这是现在的显示效果![image](https://github.com/lobehub/lobe-chat/assets/36145660/806727c9-585d-4cd8-8a7c-c91e87b2334b)

2024-07-09 08:39 UTC, arvinxx requested changes

2024-07-09 08:39 UTC, arvinxx commented on src/features/ChatInput/Topic/index.tsx
> +  useHotkeys(hotkeys, () => setConfirmOpened(true), {
PC端上快捷键就是为了快捷操作，不应该做二次确认

2024-07-09 09:11 UTC, RubuJam commented on src/features/ChatInput/Topic/index.tsx
> +  useHotkeys(hotkeys, () => setConfirmOpened(true), {
已经修改，现在使用快捷键会直接执行操作，不会进行二次确认

2024-07-11 06:55 UTC, arvinxx commented
新增的按钮不应该用警戒色，需要换成普通的，其他我没问题了

2024-07-11 14:15 UTC, arvinxx commented on src/features/ChatInput/ActionBar/Clear.tsx
> +      placement={'top'}
这个为啥改成 `top` ？

2024-07-11 14:19 UTC, RubuJam commented on src/features/ChatInput/ActionBar/Clear.tsx
> +      placement={'top'}
在某些语言中，`topright`会导致组件溢出显示区域

2024-07-11 14:35 UTC, arvinxx commented on src/features/ChatInput/ActionBar/Clear.tsx
> +      placement={'top'}
不对吧 topright 是确保右对齐的，怎么会溢出显示区呢

2024-07-12 15:00 UTC, RubuJam commented on src/features/ChatInput/ActionBar/Clear.tsx
> +      placement={'top'}
就像这样
修改后：
![2](https://github.com/lobehub/lobe-chat/assets/36145660/6a5b8f9f-b222-4b48-aaae-acb0ec4dbec8)
修改前：
![1](https://github.com/lobehub/lobe-chat/assets/36145660/89dbc97f-f216-420f-bc30-d1586af1ed78)

2024-07-12 15:00 UTC, RubuJam commented on src/features/ChatInput/ActionBar/Clear.tsx
> +      placement={'top'}
这个问题在Ant-Design中复现会更明显，我还在问那边，这个到底是bug还是feature

![fb](https://github.com/lobehub/lobe-chat/assets/36145660/37a762df-5a25-4f3a-ae3f-f3233077b100)

> 不对吧 topright 是确保右对齐的，怎么会溢出显示区呢

2024-07-13 06:38 UTC, merged