✨ feat: Add Baichuan model provider
lobehub/lobehub pull request #3097
Opened 2024-06-30 13:15 UTC by hezhijie0327

#### 💻 变更类型 | Change Type

- [X] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

基于 #2804 实现支持百川大模型

存在一个问题，frequency_penalty 预设需要在 `1-2` 范围内，默认下会出现 `frequency_penalty must be between 1 and 2 - frequencyPenalty` 错误
![image](https://github.com/lobehub/lobe-chat/assets/58100052/deba968b-12ef-46e9-98a5-eca5055b8179)
![image](https://github.com/lobehub/lobe-chat/assets/58100052/977f2151-3f89-4c50-82c6-80a16c540c9e)

#### 📝 补充信息 | Additional Information
![image](https://github.com/lobehub/lobe-chat/assets/58100052/776e82ed-9cb7-4b37-b610-7a32b2aa1928)
![image](https://github.com/lobehub/lobe-chat/assets/58100052/26e44270-8057-4ade-a5e7-6d1df1dbbd59)
![image](https://github.com/lobehub/lobe-chat/assets/58100052/1861e1fc-0137-4de5-b5c8-49cb1c24c86a)

2024-06-30 14:22 UTC, hezhijie0327 commented
修复默认 `frequency_penalty` 范围问题，自动调整，逻辑如下：
```
a. < 0: 1
b. < 1: 原值 + 1
c. > 2: 2 
d. >= 1 <= 2: 原值
e. undefined: 1
```

2024-07-01 09:03 UTC, arvinxx approved these changes
LGTM , Thanks for your contribution!

2024-07-01 09:29 UTC, arvinxx requested changes
刚测了下有个小问题：

<img width="661" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/d5ab4e93-c2fb-4f24-be01-fe25149f9dda">

报错时候的 Logo 不正确

2024-07-01 10:42 UTC, hezhijie0327 commented
> 刚测了下有个小问题：
> 
> <img alt="image" width="661" src="https://private-user-images.githubusercontent.com/28616219/344619994-d5ab4e93-c2fb-4f24-be01-fe25149f9dda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzA0NjQsIm5iZiI6MTcxOTgzMDE2NCwicGF0aCI6Ii8yODYxNjIxOS8zNDQ2MTk5OTQtZDVhYjRlOTMtYzJmYi00ZjI0LWJlMDEtZmUyNTE0OWY5ZGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEwMzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMzEzMzVhZDJmOWZiNzI0NzU2MGU3MGQwNWQyODZmOGRhMGUzNmQ4ZjNmYmY5OGU4NGZkMWM2YTM2MDBjZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vT6MZziemNVxD-TUUmhQPUSW7rfUUEC3oRoLmYN8Cyw">
> 报错时候的 Logo 不正确

欸 我想想... 印象里应该没引入 OpenAI 的图标

2024-07-01 10:45 UTC, arvinxx commented
@hezhijie0327 兜底是openai的，要看下是不是provider icon没配正确

2024-07-01 10:56 UTC, arvinxx commented
看起来是我的问题 https://github.com/lobehub/lobe-chat/blob/main/src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx 这里忘记补了

2024-07-01 10:57 UTC, arvinxx commented
这个我先合了，provider Avatar 这部分代码我来改吧。应该要提出来的

2024-07-01 10:59 UTC, merged