✨ feat: spport qwen-vl and tool call for qwen
lobehub/lobehub pull request #3114
Opened 2024-07-02 03:19 UTC by Mingholy

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

* 增加`qwen-vl`系列模型调用；
    * ![image](https://github.com/lobehub/lobe-chat/assets/14246397/97b6ee14-8f5b-44ce-aafc-541a4b0ac362)
* 增加`qwen-turbo/plus/max`对function call的支持。
    * ![image](https://github.com/lobehub/lobe-chat/assets/14246397/813b480e-ab52-43e5-82f9-ba4c1144dc89)

#### 📝 补充信息 | Additional Information

> 如果使用默认的`top_p`参数（即0.999），将会有较大概率生成不令人满意的回答。因此除了模型文档注明的不支持的参数外，`top_p`也将对vl模型禁用；

`qwen-vl`现在已经支持图像传入base64，OpenAI Compatible模式更加贴近OpenAI行为；

如需使用S3或者阿里云OSS保存上传的图片文件，需要正确配置下列环境变量，以阿里云OSS为例：
1. 需要配置AK、SK：
    * `S3_ACCESS_KEY_ID`
    * `S3_SECRET_ACCESS_KEY`
2. 需要指定OSS信息：
    * `S3_BUCKET`
    * `S3_ENDPOINT`（如`https://oss-cn-hangzhou.aliyuncs.com`）
    * `S3_REGION`（如`oss-cn-hangzhou`)
    * `NEXT_PUBLIC_S3_DOMAIN`（一般为`https://${bucket}.${endpoint}`）

2024-07-02 04:34 UTC, Mingholy commented
Woking on unit test...

2024-07-02 05:56 UTC, arvinxx commented
所以目前 qwen tool calling 是不支持流式是么？

2024-07-02 07:09 UTC, Mingholy commented
> 所以目前 qwen tool calling 是不支持流式是么？

是的，目前暂不支持`stream=True`。同时，后续如果支持`stream=True`也不支持`incremental_output=True`，所以还要看支持流式之后的效果再做修改。

2024-07-09 14:03 UTC, arvinxx requested changes

2024-07-09 14:03 UTC, arvinxx commented on src/libs/agent-runtime/qwen/index.test.ts
> +    it('should correctly list available models', async () => {
这个测试需要mock下数据，不然 qwen 的接口数据返回变了，就会直接造成 snapshot 变更，然后测试挂掉。

2024-07-11 14:30 UTC, arvinxx commented on src/libs/agent-runtime/qwen/index.test.ts
> +    it('should correctly list available models', async () => {
@Mingholy 这里改下？

2024-07-15 04:42 UTC, Mingholy commented on src/libs/agent-runtime/qwen/index.test.ts
> +    it('should correctly list available models', async () => {
这里其实没有调用模型列表接口（DashScope这边暂时也没有这样的接口可用），调用`models`时返回的是provider配置中的`chatModels`。

所以这里才使用snapshot测试，如果返回了和旧快照不同的值导致测试挂掉，应该是预期中的行为，原因是如果：
1. `models`的实现有变更，那么此处的测试代码应该同步更新；
2. `chatModels`配置有变更，那么应该更新快照后重跑测试。

如果需要mock的话那就这样处理？
```ts
beforeEach(() => {
    /* ... */
    vi.spyOn(instance, 'models').mockResolvedValue(Qwen.chatModels)
})

/* ... */

  describe('models', () => {
    it('should correctly list available models', async () => {
      const instance = new LobeQwenAI({ apiKey: 'test_api_key' });
      const models = await instance.models();
      expect(models).toEqual(Qwen.chatModels);
    });
  });

```

2024-07-15 04:42 UTC, Mingholy commented on src/libs/agent-runtime/qwen/index.test.ts
> +    it('should correctly list available models', async () => {
@arvinxx 已修改，看看是否符合预期？

2024-07-17 05:21 UTC, merged