Add new model provider Novita AI
lobehub/lobehub pull request #3177
Opened 2024-07-09 07:05 UTC by jasonhp

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

1. Add new model provider: Novita AI
2. FIx test case: OPENROUTER_MODEL_LIST, and its snapshot.

#### 📝 补充信息 | Additional Information

2024-07-09 12:56 UTC, arvinxx requested changes

2024-07-09 12:56 UTC, arvinxx commented on src/app/(main)/settings/llm/ProviderList/providers.tsx
> +      {
请放在 OpenRouter 后面，目前 OpenRouter 的用户还是比较多的，它需要靠前

2024-07-09 12:56 UTC, arvinxx commented on src/config/modelProviders/baichuan.ts
这些为啥被格式化了？

2024-07-09 12:56 UTC, arvinxx commented on src/libs/agent-runtime/baichuan/index.ts
这里也是，为什么被格式化了

2024-07-10 03:12 UTC, jasonhp commented on src/app/(main)/settings/llm/ProviderList/providers.tsx
> +      {
已调整

2024-07-10 03:12 UTC, jasonhp commented on src/config/modelProviders/baichuan.ts
已恢复

2024-07-10 03:12 UTC, jasonhp commented on src/libs/agent-runtime/baichuan/index.ts
类似格式化均已恢复

2024-07-11 14:29 UTC, arvinxx reviewed
还需要补充一篇配置文档，参考：https://lobehub.com/zh/docs/usage/providers/qwen

2024-07-13 07:46 UTC, arvinxx requested changes
是不是合并有问题，出现了很多重复添加的情况

2024-07-13 07:46 UTC, arvinxx commented on src/app/(main)/settings/llm/ProviderList/providers.tsx
> +      },
怎么重复添加了？

2024-07-13 07:46 UTC, arvinxx commented on src/components/ModelProviderIcon/index.tsx
> +    case ModelProvider.Novita: {
这里也是

2024-07-17 07:42 UTC, jasonhp commented on src/app/(main)/settings/llm/ProviderList/providers.tsx
> +      },
已修复

2024-07-17 07:42 UTC, jasonhp commented on src/components/ModelProviderIcon/index.tsx
> +    case ModelProvider.Novita: {
所有重复添加部分都已修复

2024-07-23 02:09 UTC, arvinxx approved these changes
LGTM now, Thanks for your great work!

2024-07-23 02:09 UTC, merged

2024-07-25 02:39 UTC, xenstar commented
@jasonhp Seems the get model list button doesn't work. It can't get the latest Llama 3.1 models. 

![image](https://github.com/user-attachments/assets/aa7c3a23-43d0-415b-bd79-f44a9c935543)