📝 docs: update local docker-compose auth to casdoor
lobehub/lobehub pull request #3855
Opened 2024-09-09 10:18 UTC by cy948

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [x] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

-  rename `docker-compose/local/` => `docker-compose/local-logto/`
- `docs/self-hosting/server-database/docker-compose.mdx`: 重命名后更新文档;
- `docker-compose/local/.env.example`, `docker-compose/demo/.env.zh-CN.example`: 提前定义Casdoor的环境变量;
- `docker-compose/local/docker-compose.yml`: 接入Casdoor，定义初始化行为；
- `docker-compose/local/init_data.json.tar.gz`: Casdoor初始化配置，[ref](https://casdoor.org/docs/deployment/data-initialization);
- `docker-compose/local/s3_data.tar.gz`: Minio初始化配置,
- `docker-compose/local/setup.sh`: 准备阶段脚本;

- close https://github.com/lobehub/lobe-chat/issues/3875

#### 📝 补充信息 | Additional Information

1. 使用说明：
- 下载配置
```bash
bash <(curl -fsSL https://raw.githubusercontent.com/cy948/lobe-chat/run/casdoor/docker-compose/local/setup.sh) -f -l zh_CN --url https://raw.githubusercontent.com/cy948/lobe-chat/run/casdoor
```
> 脚本参数说明：
> - `-f`: 强制下载附件
> - `-l`：选择脚本语言，有 `zh_CN` 可选，默认为en

- 修改`.env`
- 启动
```bash
docker compose up
```
- 访问 http://localhost:3210
- 登录，账号密码为：
```
admin
123
```

2. 重新生成`init_data.json`：
- 使用casdoor镜像，连接一个空的数据库，在UI界面进行操作、配置
- clone casdoor项目，运行
```
# Require go >= 1.17
go mod download
go test ./object -v -run TestDumpToFile
cd ./object
mv init_data_dump.json init_data.json
tar -czvf init_data.json.tar.gz init_data.json
```
3. 重新生成`s3_data`：
> 该部分为`minio`的挂载文件夹，`.env.example`中的`S3_*`发生变更则需要重新打包;

- 运行minio，按照[文档](https://lobehub.com/docs/self-hosting/server-database/docker-compose#configure-min-io-s-3)的方式创建Bucket和AccessKey，并进行记录;
- 根据BucketName和AccessKey修改环境变量示例`env.example`;
- 直接对文件夹进行压缩
```sh
tar -czvf s3_data.tar.gz s3_data
```

2024-09-09 16:54 UTC, arvinxx commented
这个方案是本地体验还是生产也可以用？

2024-09-10 00:17 UTC, cy948 commented
> 这个方案是本地体验还是生产也可以用？

@arvinxx 推荐本地体验，用于生产则需要更改密钥。

2024-09-11 02:58 UTC, arvinxx commented
@cy948 那就直接替换本地那个 logto 的文件夹吧。或者 logto 的改个别的名字，local-logto

2024-09-12 13:49 UTC, arvinxx commented on docker-compose/local/.env.zh-CN.example
> +# Logto secret
这里不是 logto 了吧？

2024-09-12 13:49 UTC, arvinxx commented on docker-compose/local/docker-compose.yml
> +      - 'GENERIC_OIDC_ISSUER=http://localhost:${CASDOOR_PORT}'
我感觉后面还是得要一个 CASDOOR 的 provider 的

2024-09-12 13:52 UTC, cy948 commented on docker-compose/local/docker-compose.yml
> +      - 'GENERIC_OIDC_ISSUER=http://localhost:${CASDOOR_PORT}'
对，顺便把 casdoor 的 webhook 也接了

2024-09-12 13:52 UTC, cy948 commented on docker-compose/local/.env.zh-CN.example
> +# Logto secret
对，我检查一下

2024-09-13 15:52 UTC, arvinxx commented on docker-compose/local/docker-compose.yml
>        - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
这边S3 的部分感觉可以把 LLM_VISION_IMAGE_USE_BASE64=1 加上去。

2024-09-14 11:17 UTC, cy948 commented on docker-compose/local/docker-compose.yml
>        - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
已增加 https://github.com/lobehub/lobe-chat/pull/3855/commits/ae700cda6e980e1a203ef5dcfeb9630db90441db

2024-09-15 09:37 UTC, zhuozhiyongde commented
~~睡了 20 个小时，来干活了！~~

1. 下载下来的 .env 没有根据语言参数切换
2. 应该是 docker compose up -d
3. 首先打开的应该是 8000 端口，而不是 lobe 的 3210

2024-09-15 09:48 UTC, zhuozhiyongde commented
docker compose up -d 现在也启动不起来，lobe 报错 Error: [NextAuth] provider generic-oidc is not supported

是由于相关 PR 没有合并触发 docker 的相应构建吗

2024-09-15 09:56 UTC, cy948 commented
@zhuozhiyongde 你看看是不是本地的 lobechat-database 镜像没有更新？

2024-09-15 09:57 UTC, zhuozhiyongde commented
> @zhuozhiyongde 你看看是不是本地的 lobechat-database 镜像没有更新？

我去，睡傻了

2024-09-15 10:17 UTC, zhuozhiyongde commented
4. 下载下来的 tar.gz 压缩格式没有删除

2024-09-23 16:29 UTC, arvinxx requested changes

2024-09-23 16:29 UTC, arvinxx commented on docker-compose/local/docker-compose.yml
> +      - '8000:8000'  # Casdoor Admin
这里 8000 有问题，和 env 里 `CASDOOR_PORT=8000` 冲突了，怪不得我本地一直起不来

2024-09-24 11:47 UTC, arvinxx commented
<img width="554" alt="image" src="https://github.com/user-attachments/assets/1440ddb5-0312-47c5-87e3-095aa631c11e">

为什么需要重新生成

2024-09-24 11:50 UTC, cy948 commented
> <img width="554" alt="image" src="https://github.com/user-attachments/assets/1440ddb5-0312-47c5-87e3-095aa631c11e">
> 
> 为什么需要重新生成

这部分主要是留给以后开发维护用的 如果需要改minio的配置才需要重新生成。

2024-09-24 12:00 UTC, arvinxx approved these changes
我目前测下来没问题了

2024-09-24 12:01 UTC, merged

2024-09-25 06:59 UTC, zhangleijun111 commented
> 我目前测下来没问题了

我也成功了本地，我想吧localhost全部改成ip，让内网的其他机器访问可以嘛  现在报这个错误
[
![8cf425ed427965d8af6f35cb35a0591](https://github.com/user-attachments/assets/339353e8-24bf-4fb7-9036-6044b7a5d1af)
](url)

[
![490ec76a51636f86a6282fc0d1c6461](https://github.com/user-attachments/assets/7aaa6709-40c6-4b1d-a0a1-c9c5b063dcc4)
](url)

2024-09-25 07:06 UTC, zhangleijun111 commented
> > 这个方案是本地体验还是生产也可以用？
> 
> @arvinxx 推荐本地体验，用于生产则需要更改密钥。但改密钥又会回到像logto那样复杂的配置过程，还是作为本地体验版本好点？

这个本地本地部署方便很多，但是我前面吧localhost换成ip想让其他内网机器用就不行了，另外可以支持生产部署嘛

2024-09-25 07:15 UTC, cy948 commented
> 这个本地本地部署方便很多，但是我前面吧localhost换成ip想让其他内网机器用就不行了，另外可以支持生产部署嘛

不支持，当前的本地体验版配置在网络和安全性上未达到生产要求。

2024-09-25 07:51 UTC, zhangleijun111 commented
> > 这个本地本地部署方便很多，但是我前面吧localhost换成ip想让其他内网机器用就不行了，另外可以支持生产部署嘛
> 
> 不支持，当前的本地体验版配置在网络和安全性上未达到生产要求。

那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的是吧？？？？？

2024-09-25 09:15 UTC, cy948 commented
> 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的是吧？？？？？

问题超出维护范围，不作解答，请见谅。

2024-09-25 09:18 UTC, zhangleijun111 commented
> > 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的是吧?????
> 
> 问题超出维护范围，不作解答，请见谅。

不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。

2024-09-25 09:19 UTC, zhangleijun111 commented
> > 这个本地本地部署方便很多，但是我前面吧localhost换成ip想让其他内网机器用就不行了，另外可以支持生产部署嘛
> 
> 不支持，当前的本地体验版配置在网络和安全性上未达到生产要求。

另外上casdoor的目的不就是因为logto生产部署很麻烦吗，结果你说生产居然不行。。。。

2024-09-25 09:23 UTC, cy948 commented
> 另外上casdoor的目的不就是因为logto生产部署很麻烦吗，结果你说生产居然不行。。。。

我的意思是当前pr下的本地的方案不能直接用于生产，生产方案请自行探索，不进行相关问题解答。

2024-09-25 11:49 UTC, BiFangKNT commented
> > > 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的是吧?????
> > 
> > 
> > 问题超出维护范围，不作解答，请见谅。
> 
> 不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。

哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。

2024-09-25 12:00 UTC, zhangleijun111 commented
就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase



发自我的iPhone


------------------ Original ------------------
From: 彼方 ***@***.***&gt;
Date: Wed,Sep 25,2024 7:50 PM
To: lobehub/lobe-chat ***@***.***&gt;
Cc: zhangleijun111 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [lobehub/lobe-chat] �� docs: update local docker-compose auth to casdoor (PR #3855)





    
那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的是吧?????
  
问题超出维护范围，不作解答，请见谅。
  
不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。
  
哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2024-09-25 12:04 UTC, BiFangKNT commented
> > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone
> > […](#)
> > ------------------ Original ------------------ From: 彼方 _**@**_._**> Date: Wed,Sep 25,2024 7:50 PM To: lobehub/lobe-chat _**@**_.**_> Cc: zhangleijun111 _**@**_._**>, Comment _**@**_.**_> Subject: Re: [lobehub/lobe-chat] �� docs: update local docker-compose auth to casdoor (PR #3855) 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的是吧????? 问题超出维护范围，不作解答，请见谅。 不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。 哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问

我的意思是，你lobe设置其他服务（s3那些）接入点为localhost，不影响你局域网内其他机器通过局域网ip访问

2024-09-25 12:05 UTC, zhangleijun111 commented
我明天把截图给你看吧兄弟



发自我的iPhone


------------------ Original ------------------
From: 彼方 ***@***.***&gt;
Date: Wed,Sep 25,2024 8:04 PM
To: lobehub/lobe-chat ***@***.***&gt;
Cc: zhangleijun111 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [lobehub/lobe-chat] �� docs: update local docker-compose auth to casdoor (PR #3855)





  
就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone
 …
 ------------------ Original ------------------ From: 彼方 @.&gt; Date: Wed,Sep 25,2024 7:50 PM To: lobehub/lobe-chat @.&gt; Cc: zhangleijun111 @.&gt;, Comment @.&gt; Subject: Re: [lobehub/lobe-chat] �� docs: update local docker-compose auth to casdoor (PR #3855) 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的是吧????? 问题超出维护范围，不作解答，请见谅。 不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。 哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你局域网的其他机器？那根本不影响好吧，localhost也能正常访问
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2024-09-26 01:19 UTC, zhangleijun111 commented
> > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone [...](#) ------------------ 原始------------------来自：彼方 _**@**_。_**>日期：2024 年 9 月 25 日星期三晚上 7：50 收件人：lobehub/lobe-chat _**@**_。**_> 抄送： zhangleijun111 _**@**_._**>，评论 _**@**_。**_>主题： 回复： [lobehub/lobe-chat] 文档： 更新本地 docker-compose auth 到 casdoor （PR #3855） 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的吧?????问题超出维护范围，不作解答，请见谅。不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> 
> 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问

你看看图片主要是卡在lobechat点击登录这里
[
![0ad087534044f20cced964f0ff8d721](https://github.com/user-attachments/assets/1c9d8d0e-3d01-4c35-a1b4-72338ce6cfeb)
](url)

[
![80d07d4d5094b46b951c6cfb6924922](https://github.com/user-attachments/assets/b3dfa3ed-00b6-494b-86bf-10de322dba8a)
](url)    一个是部署lob的机器，另一台是内网的机器，所以我问localhost换成ip会不会可以解决这个问题

2024-09-26 02:22 UTC, zhangleijun111 commented
> > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone [...](#) ------------------ 原始------------------来自：彼方 _**@**_。_**>日期：2024 年 9 月 25 日星期三晚上 7：50 收件人：lobehub/lobe-chat _**@**_。**_> 抄送： zhangleijun111 _**@**_._**>，评论 _**@**_。**_>主题： 回复： [lobehub/lobe-chat] 文档： 更新本地 docker-compose auth 到 casdoor （PR #3855） 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的吧?????问题超出维护范围，不作解答，请见谅。不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> 
> 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问

已经搞定了谢谢你

2024-09-26 07:41 UTC, BiFangKNT commented
> > > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone [...](#) ------------------ 原始------------------来自：彼方 _**@**_。_**>日期：2024 年 9 月 25 日星期三晚上 7：50 收件人：lobehub/lobe-chat _**@**_。**_> 抄送： zhangleijun111 _**@**_._**>，评论 _**@**_。**_>主题： 回复： [lobehub/lobe-chat] 文档： 更新本地 docker-compose auth 到 casdoor （PR #3855） 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的吧?????问题超出维护范围，不作解答，请见谅。不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> > 
> > 
> > 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问
> 
> 你看看图片主要是卡在lobechat点击登录这里 [ ![0ad087534044f20cced964f0ff8d721](https://private-user-images.githubusercontent.com/169867372/370944511-1c9d8d0e-3d01-4c35-a1b4-72338ce6cfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NTExLTFjOWQ4ZDBlLTNkMDEtNGMzNS1hMWI0LTcyMzM4Y2U2Y2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2JmM2NhMmIxOTY4Y2UxMWM1YWUzZTdkZDFhOWRlZDk0YjBlMzk0NWFlZThlZTFjNzk0NjZkMjI2YmFmMzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8RDLdat6VCy-JdsXxSI6XUE3JIYmeiWRA4G9AP-R9g8) ](url)
> 
> [ ![80d07d4d5094b46b951c6cfb6924922](https://private-user-images.githubusercontent.com/169867372/370944618-b3dfa3ed-00b6-494b-86bf-10de322dba8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NjE4LWIzZGZhM2VkLTAwYjYtNDk0Yi04NmJmLTEwZGUzMjJkYmE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWNhZDhhNzdiYmMyZDEzOTBkZDM5YTc3NGMwNjllMjAzNzUzMTEyZmMyM2IzM2RhYTM5Y2ViMjM1ZWE5MTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yU1a2R--geq6R42BHxzIAw9EXj1M1H8iD7dSWdrzSLM) ](url) 一个是部署lob的机器，另一台是内网的机器，所以我问localhost换成ip会不会可以解决这个问题

你这浏览器是哪里的服务

2024-09-26 07:45 UTC, BiFangKNT commented
> > > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone [...](#) ------------------ 原始------------------来自：彼方 _**@**_。_**>日期：2024 年 9 月 25 日星期三晚上 7：50 收件人：lobehub/lobe-chat _**@**_。**_> 抄送： zhangleijun111 _**@**_._**>，评论 _**@**_。**_>主题： 回复： [lobehub/lobe-chat] 文档： 更新本地 docker-compose auth 到 casdoor （PR #3855） 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的吧?????问题超出维护范围，不作解答，请见谅。不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> > 
> > 
> > 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问
> 
> 你看看图片主要是卡在lobechat点击登录这里 [ ![0ad087534044f20cced964f0ff8d721](https://private-user-images.githubusercontent.com/169867372/370944511-1c9d8d0e-3d01-4c35-a1b4-72338ce6cfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NTExLTFjOWQ4ZDBlLTNkMDEtNGMzNS1hMWI0LTcyMzM4Y2U2Y2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2JmM2NhMmIxOTY4Y2UxMWM1YWUzZTdkZDFhOWRlZDk0YjBlMzk0NWFlZThlZTFjNzk0NjZkMjI2YmFmMzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8RDLdat6VCy-JdsXxSI6XUE3JIYmeiWRA4G9AP-R9g8) ](url)
> 
> [ ![80d07d4d5094b46b951c6cfb6924922](https://private-user-images.githubusercontent.com/169867372/370944618-b3dfa3ed-00b6-494b-86bf-10de322dba8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NjE4LWIzZGZhM2VkLTAwYjYtNDk0Yi04NmJmLTEwZGUzMjJkYmE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWNhZDhhNzdiYmMyZDEzOTBkZDM5YTc3NGMwNjllMjAzNzUzMTEyZmMyM2IzM2RhYTM5Y2ViMjM1ZWE5MTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yU1a2R--geq6R42BHxzIAw9EXj1M1H8iD7dSWdrzSLM) ](url) 一个是部署lob的机器，另一台是内网的机器，所以我问localhost换成ip会不会可以解决这个问题

compose内部服务的localhost不等于主机的localhost啊。compose默认网络模式是bridge，默认本地网关是172.17.0.1，网段是/16，一般和你主机localhost不同的。

2024-09-26 07:54 UTC, BiFangKNT commented
> > > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone [...](#) ------------------ 原始------------------来自：彼方 _**@**_。_**>日期：2024 年 9 月 25 日星期三晚上 7：50 收件人：lobehub/lobe-chat _**@**_。**_> 抄送： zhangleijun111 _**@**_._**>，评论 _**@**_。**_>主题： 回复： [lobehub/lobe-chat] 文档： 更新本地 docker-compose auth 到 casdoor （PR #3855） 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的吧?????问题超出维护范围，不作解答，请见谅。不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> > 
> > 
> > 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问
> 
> 你看看图片主要是卡在lobechat点击登录这里 [ ![0ad087534044f20cced964f0ff8d721](https://private-user-images.githubusercontent.com/169867372/370944511-1c9d8d0e-3d01-4c35-a1b4-72338ce6cfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NTExLTFjOWQ4ZDBlLTNkMDEtNGMzNS1hMWI0LTcyMzM4Y2U2Y2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2JmM2NhMmIxOTY4Y2UxMWM1YWUzZTdkZDFhOWRlZDk0YjBlMzk0NWFlZThlZTFjNzk0NjZkMjI2YmFmMzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8RDLdat6VCy-JdsXxSI6XUE3JIYmeiWRA4G9AP-R9g8) ](url)
> 
> [ ![80d07d4d5094b46b951c6cfb6924922](https://private-user-images.githubusercontent.com/169867372/370944618-b3dfa3ed-00b6-494b-86bf-10de322dba8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NjE4LWIzZGZhM2VkLTAwYjYtNDk0Yi04NmJmLTEwZGUzMjJkYmE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWNhZDhhNzdiYmMyZDEzOTBkZDM5YTc3NGMwNjllMjAzNzUzMTEyZmMyM2IzM2RhYTM5Y2ViMjM1ZWE5MTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yU1a2R--geq6R42BHxzIAw9EXj1M1H8iD7dSWdrzSLM) ](url) 一个是部署lob的机器，另一台是内网的机器，所以我问localhost换成ip会不会可以解决这个问题

你compose内部服务要不用localhost要不用ip，localhost是无脑设置，ip你还要分清楚是用容器内部ip还是宿主机ip，你看你这不混淆了吗？这是compose内容器间的互相访问设置，你外部要访问lobe，肯定得用映射到容器外端口，你也没告诉咱你的casdoor端口是怎么映射的，咱如何定位问题？你每次都这样，每次改动配置都不声明改动了哪里，从什么基础上改动的，前文在哪里，就好像把github当qq群了一样，很多热心大佬和你聊到一半就不说话了，大抵就是因为这个原因，你明白吗？

2024-09-26 08:18 UTC, zhangleijun111 commented
> > > > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone [...](#) ------------------ 原始------------------来自：彼方 _**@**_。_**>日期：2024 年 9 月 25 日星期三晚上 7：50 收件人：lobehub/lobe-chat _**@**_。**_> 抄送： zhangleijun111 _**@**_._**>，评论 _**@**_。**_>主题： 回复： [lobehub/lobe-chat] 文档： 更新本地 docker-compose auth 到 casdoor （PR #3855） 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的吧?????问题超出维护范围，不作解答，请见谅。不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> > > 
> > > 
> > > 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问
> > 
> > 
> > 你看看图片主要是卡在lobechat点击登录这里[ ![0ad087534044f20cced964f0ff8d721](https://private-user-images.githubusercontent.com/169867372/370944511-1c9d8d0e-3d01-4c35-a1b4-72338ce6cfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NTExLTFjOWQ4ZDBlLTNkMDEtNGMzNS1hMWI0LTcyMzM4Y2U2Y2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2JmM2NhMmIxOTY4Y2UxMWM1YWUzZTdkZDFhOWRlZDk0YjBlMzk0NWFlZThlZTFjNzk0NjZkMjI2YmFmMzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8RDLdat6VCy-JdsXxSI6XUE3JIYmeiWRA4G9AP-R9g8) ](url)
> > [ ![80d07d4d5094b46b951c6cfb6924922](https://private-user-images.githubusercontent.com/169867372/370944618-b3dfa3ed-00b6-494b-86bf-10de322dba8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NjE4LWIzZGZhM2VkLTAwYjYtNDk0Yi04NmJmLTEwZGUzMjJkYmE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWNhZDhhNzdiYmMyZDEzOTBkZDM5YTc3NGMwNjllMjAzNzUzMTEyZmMyM2IzM2RhYTM5Y2ViMjM1ZWE5MTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yU1a2R--geq6R42BHxzIAw9EXj1M1H8iD7dSWdrzSLM) ](url)一个是部署lob的机器，另一台是内网的机器，所以我问localhost换成ip会不会可以解决这个问题
> 
> 你compose内部服务要不用localhost要不用ip，localhost是无脑设置，ip你还要分清楚是用容器内部ip还是宿主机ip，你看你这不混淆了吗？这是compose内容器间的互相访问设置，你外部要访问lobe，肯定得用映射到容器外端口，你也没告诉咱你的casdoor端口是怎么映射的，咱如何定位问题？你每次都这样，每次改动配置都不声明改动了哪里，从什么基础上改动的，前文在哪里，就好像把github当qq群了一样，很多热心大佬和你聊到一半就不说话了，大抵就是因为这个原因，你明白吗？

我已经搞定了啊兄弟，没有你想的这么复杂的，是你吧问题搞的复杂化了不存在端口映射容器互通哈哈哈哈，另外现在excel是还不可以分块的是吧

2024-09-26 09:01 UTC, BiFangKNT commented
> > > > > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone [...](#) ------------------ 原始------------------来自：彼方 _**@**_。_**>日期：2024 年 9 月 25 日星期三晚上 7：50 收件人：lobehub/lobe-chat _**@**_。**_> 抄送： zhangleijun111 _**@**_._**>，评论 _**@**_。**_>主题： 回复： [lobehub/lobe-chat] 文档： 更新本地 docker-compose auth 到 casdoor （PR #3855） 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的吧?????问题超出维护范围，不作解答，请见谅。不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> > > > 
> > > > 
> > > > 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问
> > > 
> > > 
> > > 你看看图片主要是卡在lobechat点击登录这里[ ![0ad087534044f20cced964f0ff8d721](https://private-user-images.githubusercontent.com/169867372/370944511-1c9d8d0e-3d01-4c35-a1b4-72338ce6cfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NTExLTFjOWQ4ZDBlLTNkMDEtNGMzNS1hMWI0LTcyMzM4Y2U2Y2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2JmM2NhMmIxOTY4Y2UxMWM1YWUzZTdkZDFhOWRlZDk0YjBlMzk0NWFlZThlZTFjNzk0NjZkMjI2YmFmMzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8RDLdat6VCy-JdsXxSI6XUE3JIYmeiWRA4G9AP-R9g8) ](url)
> > > [ ![80d07d4d5094b46b951c6cfb6924922](https://private-user-images.githubusercontent.com/169867372/370944618-b3dfa3ed-00b6-494b-86bf-10de322dba8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NjE4LWIzZGZhM2VkLTAwYjYtNDk0Yi04NmJmLTEwZGUzMjJkYmE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWNhZDhhNzdiYmMyZDEzOTBkZDM5YTc3NGMwNjllMjAzNzUzMTEyZmMyM2IzM2RhYTM5Y2ViMjM1ZWE5MTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yU1a2R--geq6R42BHxzIAw9EXj1M1H8iD7dSWdrzSLM) ](url)一个是部署lob的机器，另一台是内网的机器，所以我问localhost换成ip会不会可以解决这个问题
> > 
> > 
> > 你compose内部服务要不用localhost要不用ip，localhost是无脑设置，ip你还要分清楚是用容器内部ip还是宿主机ip，你看你这不混淆了吗？这是compose内容器间的互相访问设置，你外部要访问lobe，肯定得用映射到容器外端口，你也没告诉咱你的casdoor端口是怎么映射的，咱如何定位问题？你每次都这样，每次改动配置都不声明改动了哪里，从什么基础上改动的，前文在哪里，就好像把github当qq群了一样，很多热心大佬和你聊到一半就不说话了，大抵就是因为这个原因，你明白吗？
> 
> 我已经搞定了啊兄弟，没有你想的这么复杂的，是你吧问题搞的复杂化了不存在端口映射容器互通哈哈哈哈，另外现在excel是还不可以分块的是吧

所以你到底是怎么搞定的呢？问题出在哪呢？我也好奇啊。另外咱哪可能一上来就说中问题啊，咱讲的不也是推测吗，咱又不是项目制作组成员，咱只是一个路过的热心网友罢了

2024-09-26 10:00 UTC, zhangleijun111 commented
> > > > > > 就是我部署完成其他机器访问我这台机器的ip：3210可以正常认证和使用lobedatabase 发自我的iPhone [...](#) ------------------ 原始------------------来自：彼方 _**@**_。_**>日期：2024 年 9 月 25 日星期三晚上 7：50 收件人：lobehub/lobe-chat _**@**_。**_> 抄送： zhangleijun111 _**@**_._**>，评论 _**@**_。**_>主题： 回复： [lobehub/lobe-chat] 文档： 更新本地 docker-compose auth 到 casdoor （PR #3855） 那我把localhost换成ip给内网其他机器访问，报前面这个错误是正常的吧?????问题超出维护范围，不作解答，请见谅。不是啊正常我的理解localhost全部变成部署这台机器的ip的话，其他机器通过访问ip：3210就能实现生产的效果了，这样也能实现我要到的效果了，问题是不行。哥们，我不理解你所谓的生产环境是什么环境，不理解你为什么执着于把localhost改成局域网ip。这俩没有本质上的不同啊。— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> > > > > 
> > > > > 
> > > > > 你局域网的其他机器？那根本不影响好吧，localhost也能正常访问
> > > > 
> > > > 
> > > > 你看看图片主要是卡在lobechat点击登录这里[ ![0ad087534044f20cced964f0ff8d721](https://private-user-images.githubusercontent.com/169867372/370944511-1c9d8d0e-3d01-4c35-a1b4-72338ce6cfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NTExLTFjOWQ4ZDBlLTNkMDEtNGMzNS1hMWI0LTcyMzM4Y2U2Y2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2JmM2NhMmIxOTY4Y2UxMWM1YWUzZTdkZDFhOWRlZDk0YjBlMzk0NWFlZThlZTFjNzk0NjZkMjI2YmFmMzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8RDLdat6VCy-JdsXxSI6XUE3JIYmeiWRA4G9AP-R9g8) ](url) [ ![80d07d4d5094b46b951c6cfb6924922](https://private-user-images.githubusercontent.com/169867372/370944618-b3dfa3ed-00b6-494b-86bf-10de322dba8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzY2MzUsIm5iZiI6MTcyNzMzNjMzNSwicGF0aCI6Ii8xNjk4NjczNzIvMzcwOTQ0NjE4LWIzZGZhM2VkLTAwYjYtNDk0Yi04NmJmLTEwZGUzMjJkYmE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzM4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWNhZDhhNzdiYmMyZDEzOTBkZDM5YTc3NGMwNjllMjAzNzUzMTEyZmMyM2IzM2RhYTM5Y2ViMjM1ZWE5MTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yU1a2R--geq6R42BHxzIAw9EXj1M1H8iD7dSWdrzSLM) ](url)一个是部署lob的机器，另一台是内网的机器，所以我问localhost换成ip会不会可以解决这个问题
> > > 
> > > 
> > > 你compose内部服务要不用localhost要不用ip，localhost是无脑设置，ip你还要分清楚是用容器内部ip还是宿主机ip，你看你这不混淆了吗？这是compose内容器间的互相访问设置，你外部要访问lobe，肯定得用映射到容器外端口，你也没告诉咱你的casdoor端口是怎么映射的，咱如何定位问题？你每次都这样，每次改动配置都不声明改动了哪里，从什么基础上改动的，前文在哪里，就好像把github当qq群了一样，很多热心大佬和你聊到一半就不说话了，大抵就是因为这个原因，你明白吗？
> > 
> > 
> > 我已经搞定了啊兄弟，没有你想的这么复杂的，是你吧问题搞的复杂化了不存在端口映射容器互通哈哈哈哈，另外现在excel是还不可以分块的是吧
> 
> 所以你到底是怎么搞定的呢？问题出在哪呢？我也好奇啊。另外咱哪可能一上来就说中问题啊，咱讲的不也是推测吗，咱又不是项目制作组成员，咱只是一个路过的热心网友罢了

我就是全部把localhost换了ip重新部署了一遍就好了，不存在什么容器互通的问题其实，excel现在还不支持是吧？？？

2024-09-26 11:12 UTC, BiFangKNT commented
@zhangleijun111 
> 我就是全部把localhost换了ip重新部署了一遍就好了，不存在什么容器互通的问题其实

那么问题就出在你对ip设置的疏漏或误解混淆上了。

> excel现在还不支持是吧？？？

是的，目前测过的格式中，只有txt和ts格式支持
![image](https://github.com/user-attachments/assets/72bc99fb-95e6-43db-849d-c8d6eb6e19bd)

2024-09-26 11:20 UTC, BiFangKNT commented
@zhangleijun111 建议关注这个讨论 #3550