💄 style: add o1-preview and o1-mini model to github model provider
lobehub/lobehub pull request #4127
Opened 2024-09-25 06:49 UTC by ymefg

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

补充 OpenAI o1-mini 和 OpenAI o1-preview 到 GitHub 的模型列表。

#### 📝 补充信息 | Additional Information

2024-09-25 14:04 UTC, arvinxx requested changes

2024-09-25 14:04 UTC, arvinxx commented on src/libs/agent-runtime/github/index.ts
> +export const pruneO1Payload = (payload: ChatStreamPayload) => ({
o1Models 和 pruneO1Payload 这两部分应该直接从 OpenAI 实现处引入

2024-09-25 15:30 UTC, ymefg commented on src/libs/agent-runtime/github/index.ts
> +export const pruneO1Payload = (payload: ChatStreamPayload) => ({
搞定了

2024-09-26 15:10 UTC, arvinxx approved these changes
LGTM

2024-09-27 02:16 UTC, merged