Using env to custom title, description, prompt for default assistance
lobehub/lobehub pull request #4148
Opened 2024-09-26 04:03 UTC by khanhduyvt0101

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change
Using env to custom title, description, prompt for default assistance

2024-09-26 14:59 UTC, arvinxx commented
@khanhduyvt0101 hi, could you please seperate a PR just for the code format & lint fix? I think this PR should focus on the customize~

2024-09-27 02:33 UTC, khanhduyvt0101 commented
@arvinxx , Please consider and merge this PR man

2024-09-27 02:39 UTC, arvinxx commented
@khanhduyvt0101 yeah, I think this idea is great. I'm reviewing the code now

2024-09-27 07:30 UTC, arvinxx requested changes

2024-09-27 07:30 UTC, arvinxx commented on src/store/session/slices/session/selectors/meta.ts
need a test here for title and description

2024-09-27 07:30 UTC, arvinxx commented on src/app/(main)/chat/@session/features/SessionListContent/Inbox/index.tsx
> +  const { enableCommercialInbox } = useServerConfigStore(featureFlagsSelectors);
as there a multi-time repeat the inboxDisplayTitle, I think it's better to create a hook for InboxMeta, like 

```ts
const { title, desc, avatar }= useInboxAgentMeta();
```

and also need to create a UT for this hooks

2024-09-27 09:37 UTC, khanhduyvt0101 commented
I updated the code, please consider and merge it @arvinxx

2024-09-27 11:32 UTC, khanhduyvt0101 commented
Just updated based on your review @arvinxx

2024-10-01 09:30 UTC, arvinxx reviewed
the `custom` locale may not be a good pattern. Because most lobechat users don't need this file but it will be bundled to all users. Need to discuss a better way to handle it

2024-10-01 09:30 UTC, arvinxx commented on src/config/featureFlags/schema.ts
`commercial_inbox` -> `commercial_custom_inbox_assistant`

2024-10-01 09:30 UTC, arvinxx commented on src/const/guide.ts
If I just want inbox prompt to be empty, how to deal with it?

2024-10-02 03:49 UTC, khanhduyvt0101 commented
> the `custom` locale may not be a good pattern. Because most users don't need this file but it will be bundled to all users. Need to discuss a better way to handle it

Hi @arvinxx , if we don't use the locales, we cannot automatically generate multiple languages. Do you have any suggestions?

2024-10-02 04:34 UTC, khanhduyvt0101 commented
> the `custom` locale may not be a good pattern. Because most users don't need this file but it will be bundled to all users. Need to discuss a better way to handle it

Hi @arvinxx, I updated the code base based on your feedback. The custom locales only generate when `isCustomBranding=true`

2024-10-07 04:07 UTC, khanhduyvt0101 commented
Hi @arvinxx , Could you please help me re-consider this PR?

2025-04-09 14:18 UTC, closed without merging