:memo: docs(self hosting): Add deployment link for Alibaba Cloud
lobehub/lobehub pull request #4309
Opened 2024-10-10 02:15 UTC by LYH-RAIN

* 📝 doc : Add self-hosting support for Alibaba Cloud.

2024-10-11 08:17 UTC, arvinxx requested changes

2024-10-11 08:17 UTC, arvinxx commented on README.md
not recommend to add it in the English README, due to the deploy link is a Chinese product page, not an international page. Please revert this upadte or use an international version

2024-10-12 01:38 UTC, LYH-RAIN commented on README.md
The quick deployment link supports both Alibaba Cloud's domestic and international sites, and overseas users will automatically access the quick deployment link for the international site.

2024-10-12 01:42 UTC, LYH-RAIN commented on README.md
![image](https://github.com/user-attachments/assets/7d85601a-a7ed-438f-a9f9-e71fa5696a4f)
![image](https://github.com/user-attachments/assets/0c39f84c-523e-4336-88b7-7d0d0fff6c36)
Like this. Additionally, the deployment instructions and tutorials for Alibaba Cloud's international site are provided in English only.

2024-10-12 02:39 UTC, arvinxx commented on README.md
> The quick deployment link supports both Alibaba Cloud's domestic and international sites, and overseas users will automatically access the quick deployment link for the international site.

How you detect the international users? I try with English locale in browser and oversea VPN, but it just redirect to the domestic site

<img width="1915" alt="image" src="https://github.com/user-attachments/assets/fe2fc5d6-734d-44ec-88bb-cac4fb0d8c05">

2024-10-12 03:14 UTC, LYH-RAIN commented on README.md
Okay, we did overlook this issue, and we will address it later. We will first retract this update and replace it with another PR.
https://github.com/lobehub/lobe-chat/pull/4331

2024-10-14 02:27 UTC, closed without merging