[WIP] ✨ feat: Add TTS & STT
lobehub/lobehub pull request #443
Opened 2023-11-11 14:55 UTC by canisminor1990

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

#### 📝 补充信息 | Additional Information

2023-11-13 03:21 UTC, arvinxx requested changes

2023-11-13 03:21 UTC, arvinxx commented on next.config.mjs
> +  transpilePackages: ['@lobehub/ui', '@lobehub/tts', 'antd-style', 'lodash-es'],
试了下 next 14 似乎不需要指定 `transpilePackages` 了，这一行应该可以直接删了

2023-11-13 03:21 UTC, arvinxx commented on src/app/api/tts/microsoft-speech/route.ts
> +  return new Response(res.body, res);
`new Response(res.body, res)` 的写法很奇怪。 如果 res 本身就是  Response 类型，直接return 就好了。不需要这么写

2023-11-13 03:21 UTC, arvinxx commented on src/app/chat/features/ChatInput/ActionBar/config.ts
> +export const leftActionList = ['model', 'temperature', 'history'];
为啥这里去掉 token 了

2023-11-13 03:21 UTC, arvinxx commented on src/app/chat/features/ChatInput/STT/index.tsx
我感觉终态的 STT 交互 web 和 mobile 应该不是用一套的。先这么写吧。后面重构

2023-11-13 03:21 UTC, arvinxx commented on src/config/client.ts
> +  MICROSOFT_SPEECH_PROXY_URL: process.env.MICROSOFT_SPEECH_PROXY_URL || '/api/tts/microsoft-speech',
要加前缀，否则没用：`process.env.NEXT_PUBLIC_MICROSOFT_SPEECH_PROXY_URL`

2023-11-13 03:21 UTC, arvinxx commented on src/features/AgentSetting/AgentTTS/index.tsx
> +  const openaiVoiceOptions = useMemo(() => getOpenaiVoiceOptions(), []);
为啥要这么写？如果是个静态变量的话，放到组件外部？

2023-11-13 05:12 UTC, canisminor1990 commented on src/app/chat/features/ChatInput/ActionBar/config.ts
> +export const leftActionList = ['model', 'temperature', 'history'];
token放到最后

2023-11-13 05:24 UTC, arvinxx commented on src/app/chat/features/ChatInput/ActionBar/config.ts
> +export const leftActionList = ['model', 'temperature', 'history'];
Token也需要支持配置的，不应该在config之外。

2023-11-13 06:20 UTC, canisminor1990 commented on src/app/chat/features/ChatInput/ActionBar/config.ts
> +export const leftActionList = ['model', 'temperature', 'history'];
单独加个开关？

2023-11-14 12:13 UTC, arvinxx requested changes

2023-11-14 12:13 UTC, arvinxx commented on src/app/api/tts/microsoft-speech/route.ts
> +  return await fetchMicrosoftSpeech(req);
不需要 await

2023-11-14 12:13 UTC, arvinxx commented on src/services/tts.ts
services 是前端调用层，不应该引入 server 的文件

2023-11-14 12:13 UTC, arvinxx commented on src/hooks/useSTT.ts
> +      useSelectedSTT = isPersisted ? usePersistedSpeechRecognition : useSpeechRecognition;
这里的 usePersistedSpeechRecognition 是什么缓存逻辑？

2023-11-14 12:13 UTC, arvinxx commented on src/app/chat/(desktop)/features/ChatInput/Footer.tsx
这个文件应该要删掉了

2023-11-15 06:38 UTC, arvinxx commented on .i18nrc.js
> +  modelName: 'gpt-3.5-turbo-1106',
这个我感觉不用改，因为再过 1 个月就会自动更新了。到时候又要再改回来

2023-11-15 09:17 UTC, onlinedear commented
真的太cool了

2023-11-18 17:39 UTC, canisminor1990 commented
@arvinxx 检查一下第一版，本地文件存储还没做

2023-11-19 13:34 UTC, arvinxx commented on src/app/chat/features/Conversation/ChatList/Extras/AudioPlayer.tsx
这个文件是不是可以删了

2023-11-19 13:40 UTC, arvinxx approved these changes

2023-11-19 13:43 UTC, merged

2024-01-02 02:23 UTC, qgbcs commented
@lobehub/tts  是一个使用 TS 语言开发的，高质量 TTS  npm 包，支持在服务端和浏览器中使用。
在服务端/桌面端，只要使用 15 行代码，即可实现对标 OpenAI TTS 服务的高质量语音生成能力。目前支持 EdgeSpeechTTS 与 MicrosoftTTS 两个免费的接口，与OpenAITTS、OpenAISTT 需要用 key 的