Create btpanel.zh-CN.mdx
lobehub/lobehub pull request #4528
Opened 2024-10-29 02:44 UTC by bestlaw66

希望可以加入宝塔面板部署教程，面板这边安装帮助可以跳转官网，论坛可增加部署咱们应用的教程，详情沟通可联系qq1115070458

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

#### 📝 补充信息 | Additional Information

2024-10-29 12:56 UTC, arvinxx requested changes

2024-10-29 12:56 UTC, arvinxx commented on docs/self-hosting/platform/btpanel.zh-CN.mdx
如果不带配置步骤，请补充详细的截图说明。另外是否需要添加宝塔面板的英文版部署文档？宝塔是否有国际版用户？

2024-10-30 01:33 UTC, bestlaw66 commented on docs/self-hosting/platform/btpanel.zh-CN.mdx
有国际版的  传图片会有破图的情况，方便的话可以加个企业微信吗
![Wechat](https://github.com/user-attachments/assets/90c99ae5-4ed8-448f-a39a-5f49e15b0a66)

2024-10-31 02:15 UTC, arvinxx approved these changes
LGTM now. Thanks for your contribution!

2024-10-31 02:15 UTC, merged

2024-10-31 03:46 UTC, canisminor1990 commented
@bestlaw66 能提供下宝塔的 svg icon 么

2024-10-31 03:52 UTC, bestlaw66 commented
恸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lobehub/lobe-chat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月31日(星期四) 中午11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lobehub/lobe-chat] 📝 docs: add deployment on btpanel (PR #4528)





 
@bestlaw66 能提供下宝塔的 svg icon 么
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-10-31 04:02 UTC, canisminor1990 commented
https://lobehub.com/zh/docs/self-hosting/platform/btpanel

2024-10-31 04:13 UTC, bestlaw66 commented
https://www.bt.cn/bbs/forum.php?mod=viewthread&amp;tid=139747&amp;extra=page%3D1%26filter%3Dtypeid%26typeid%3D10
&nbsp;


恸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月31日(星期四) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lobehub/lobe-chat] 📝 docs: add deployment on btpanel (PR #4528)














 
https://lobehub.com/zh/docs/self-hosting/platform/btpanel
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;