chore: allow users to disable SSRF or set a whitelist
lobehub/lobehub pull request #4633
Opened 2024-11-07 01:04 UTC by coulsontl

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [x] 🔨 chore

#### 🔀 变更说明 | Description of Change
允许用户主动关闭ssrf或者设置白名单，解决国内机器部署时，如果使用代理且模式为FakeIP时无法使用画图的问题。

新增环境变量：
* SSRF_ALLOW_IP_ADDRESS_LIST
* SSRF_ALLOW_META_IP_ADDRESS
* SSRF_ALLOW_PRIVATE_IP_ADDRESS
* SSRF_DENY_IP_ADDRESS_LIST
参考文档：https://www.npmjs.com/package/request-filtering-agent

#### 📝 补充信息 | Additional Information
https://github.com/lobehub/lobe-chat/issues/4299 | https://github.com/lobehub/lobe-chat/issues/4470 | https://github.com/lobehub/lobe-chat/issues/4149

2024-11-07 08:35 UTC, arvinxx requested changes
另外需要补充下文档

2024-11-07 08:35 UTC, arvinxx commented on src/app/(backend)/webapi/proxy/route.ts
> +      allowIPAddressList: process.env.SSRF_ALLOW_IP_ADDRESS_LIST?.split(',') || [],
env 需要配在这里 https://github.com/lobehub/lobe-chat/blob/main/src/config/app.ts 然后读

2024-11-07 15:01 UTC, coulsontl commented on src/app/(backend)/webapi/proxy/route.ts
> +      allowIPAddressList: process.env.SSRF_ALLOW_IP_ADDRESS_LIST?.split(',') || [],
@arvinxx 已更新文档，并把env配置到了app.ts里；同时为了降低配置难度，把环境变量精简到了2个，麻烦重新review一下

2024-11-09 08:05 UTC, arvinxx commented on src/config/app.ts
> +        process.env.SSRF_ALLOW_PRIVATE_IP_ADDRESS?.toLowerCase() === 'true',
建议使用 `SSRF_ALLOW_PRIVATE_IP_ADDRESS=1`

2024-11-09 08:05 UTC, arvinxx commented on docs/self-hosting/environment-variables/basic.zh-CN.mdx
> +- 描述：允许连接的私有IP地址列表，多个IP地址时使用逗号分隔。当SSRF_ALLOD_PRIVATE_IP_ADDRESS为FALSE时才会生效。
`SSRF_ALLOD_PRIVATE_IP_ADDRESS` ，加上 ``

2024-11-09 08:05 UTC, arvinxx commented on docs/self-hosting/environment-variables/basic.zh-CN.mdx
> +- 默认值：false
默认值：0

2024-11-09 13:37 UTC, coulsontl commented on docs/self-hosting/environment-variables/basic.zh-CN.mdx
> +- 默认值：false
@arvinxx 佬，上面提到的规范都已修改，麻烦再重新review下，感谢

2024-11-09 13:45 UTC, arvinxx approved these changes
LGTM now, Thanks for your contribution!

2024-11-09 13:45 UTC, merged