♻️ refactor: refactor `languageModel` generate
lobehub/lobehub pull request #4649
Opened 2024-11-09 01:56 UTC by hezhijie0327

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [X] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change
1. 引入 `generateLLMConfig()` 并生成 `languageModel`
2. 覆写 `Bedrock` 配置，`ENABLED_AWS_BEDROCK`, `AWS_BEDROCK_MODEL_LIST`
3. `Azure` 及 `Ollama` 特殊配置引入

#### 📝 补充信息 | Additional Information

2024-11-09 09:11 UTC, arvinxx commented on src/server/globalConfig/index.ts
> +export const generateLLMConfig = () => {
要补下单测。可以让 sonnet 3.5 生成一波

2024-11-09 11:49 UTC, hezhijie0327 commented on src/server/globalConfig/index.ts
> +export const generateLLMConfig = () => {
加上了

2024-11-11 17:45 UTC, arvinxx commented on src/utils/genLLMConfig.ts
这个文件应该放在 `utils/server` 下吧，或者就放在 `server/globalConfig` 下也行？

2024-11-11 17:48 UTC, arvinxx requested changes
哦 仔细看了下，这样实现有问题的。 

const/settings 里放的是 client 的配置，而 server/globalConfig 里地方的是 server 的配置。

不能 client 和 server 同时引入统一个 genLLMConfig.ts 文件（核心问题是 client 不能引入 server 的代码）

2024-11-11 17:49 UTC, arvinxx commented on src/const/settings/llm.ts
> +export const DEFAULT_LLM_CONFIG = genUserLLMConfig();
这里应该把非常规的配置注入在这里展示出来。不然改配置还得进去这个 util 里，失去配置的作用了，比如  ollama 的 

{
    fetchOnClient: true,
}

2024-11-12 00:56 UTC, hezhijie0327 commented on src/utils/genLLMConfig.ts
ok 那就放回 `server/globalConfig` 吧

2024-11-12 00:57 UTC, hezhijie0327 commented on src/const/settings/llm.ts
> +export const DEFAULT_LLM_CONFIG = genUserLLMConfig();
已实现外部参数引入
```
export const DEFAULT_LLM_CONFIG = genUserLLMConfig({
  ollama: {
    enabled: true,
    fetchOnClient: true,
  },
  openai: {
    enabled: true,
  },
});
```

2024-11-12 01:06 UTC, arvinxx commented on src/const/settings/llm.ts
> +import { genUserLLMConfig } from '@/server/globalConfig/genLLMConfig'
这个还是我说的那个问题哈，把 genUserLLMConfig 单独拆出来提到 utils 里吧。这个是 client 也会使用的方法

2024-11-12 02:14 UTC, hezhijie0327 commented on src/const/settings/llm.ts
> +import { genUserLLMConfig } from '@/server/globalConfig/genLLMConfig'
嗯嗯 刚刚有点事做了一半... 拆分出去了

2024-11-12 02:34 UTC, arvinxx commented on src/server/globalConfig/genServerLLMConfig.ts
> +  const specificConfig: Record<any, any> = {
`specificConfig` 这一段应该也放在 index.ts 那边注入

2024-11-12 02:34 UTC, arvinxx commented on src/utils/genUserLLMConfig.ts
这个也要补下单测

2024-11-12 03:22 UTC, hezhijie0327 commented on src/utils/genUserLLMConfig.ts
加上了

2024-11-12 03:22 UTC, hezhijie0327 commented on src/server/globalConfig/genServerLLMConfig.ts
> +  const specificConfig: Record<any, any> = {
已支持

2024-11-12 03:24 UTC, arvinxx approved these changes
LGTM now. Thanks for your contribution~

2024-11-12 13:24 UTC, merged