[WIP] ⚡️feat: Support using env variable to set preferredRegion for OpenAI Edge Functions.
lobehub/lobehub pull request #473
Opened 2023-11-18 02:48 UTC by skyf0cker

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change
https://github.com/lobehub/lobe-chat/issues/470
Support using env variable to set preferredRegion for OpenAI Edge Functions.
#### 📝 补充信息 | Additional Information

2023-11-18 12:39 UTC, skyf0cker commented
@arvinxx I have done the issue by using `regions` instead of `preferredRegion`. I don't know why `preferredRegion` not work when i test in vercel. Please help to review the code changes. 😊

2023-11-18 15:28 UTC, arvinxx requested changes

2023-11-18 15:28 UTC, arvinxx commented on src/app/api/openai/chat/route.ts
> +export const config = {
这里的配置不对。 app router 下不是采用 config 的。是直接export preferredRegion

2023-11-18 15:34 UTC, skyf0cker commented on src/app/api/openai/chat/route.ts
> +export const config = {
我不太清楚具体的问题，因为对 Next.js 不是很熟悉，但是我之前是设置了 preferredRegion，但是在 Vercel 上进行测试的时候，从浏览器的请求回复中的 `x-vercel-id` 和日志来看，应该都还是打到了 hkg1 的 region，但是这样设置了以后，反而从 log 中有了 sfo1 的 Location

2023-11-18 15:51 UTC, skyf0cker commented on src/app/api/openai/chat/route.ts
> +export const config = {
现在测试又都不一样了，感觉好奇怪，我会先按照你前面提到的文档改回到 `preferredRegion`，如果你们有时间可以再确认一下这个问题，我实在对 Next 不是很了解

2023-11-18 16:11 UTC, skyf0cker commented on src/app/api/openai/chat/route.ts
> +export const config = {
我可以贴一下我在两个分支测试的结果：
设置 preferredRegion 的：
![image](https://github.com/lobehub/lobe-chat/assets/32331521/5ca81167-d605-492f-8d6f-24c21b95084d)

设置 regions 的：
![image](https://github.com/lobehub/lobe-chat/assets/32331521/ea802669-28d2-449b-876c-7793fb433b82)
@arvinxx

2023-11-19 06:23 UTC, arvinxx commented on src/app/api/openai/chat/route.ts
> +export const config = {
Nextjs 在 App Router 和 Page Router 下，配置的方式不一样。

在 App Router 下是

```ts
export const runtime = 'edge'; // 'nodejs' is the default
export const preferredRegion = 'iad1'; // only execute this function on iad1
```

在 Page Router 下是
```ts

export const config = {
  runtime: 'edge', // this is a pre-requisite
  regions: ['iad1'], // only execute this function in iad1
};
```

现在 LobeChat 使用的是 App Router，所以要用上面这种方式

2023-11-19 13:03 UTC, skyf0cker commented
@arvinxx 按照要求修改了

2023-11-20 03:11 UTC, arvinxx commented
@skyf0cker ci is failed

2023-11-20 03:31 UTC, skyf0cker commented
> @skyf0cker ci is failed

Have fixed it, waiting for approval for re-running ci

2023-11-20 03:34 UTC, canisminor1990 commented
> @skyf0cker ci is failed

tti stt 也需要同样添加一下吧？

2023-11-20 03:36 UTC, skyf0cker commented
> > @skyf0cker @arvinxx
> 
> tts stt 也需要同样添加一下吧？
> 
> `getPreferredRegion` 可以抽出来

好的，我今天抽时间做一下，看起来有代码测试覆盖率的要求，我晚一点看看一起解决一下

2023-11-21 09:47 UTC, skyf0cker commented
@arvinxx @canisminor1990 Have changed the code and add more tests.

2023-11-21 12:50 UTC, arvinxx approved these changes
good job!

2023-11-21 12:52 UTC, merged