feat: add Higress ai model provider
lobehub/lobehub pull request #4755
Opened 2024-11-22 07:45 UTC by WindWaving

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change
设置-语言模型新增支持Higress AI provider

#### 📝 补充信息 | Additional Information
##### 语言模型新增Higress provider
![image](https://github.com/user-attachments/assets/6c535979-904d-4b6f-9756-f8ddeec77ca9)
##### 对话信息
![image](https://github.com/user-attachments/assets/5f5c9fd2-5c41-4bf8-b6c1-44c411cb8494)
![image](https://github.com/user-attachments/assets/5b19aa5f-bf48-4dcc-998e-f4c9076ae940)

2024-11-26 13:09 UTC, arvinxx requested changes
Rebase 下 main，lodash 那个改下，其他没问题了~

2024-11-26 13:09 UTC, arvinxx commented on src/libs/agent-runtime/higress/index.ts
> +import { uniqueId } from 'lodash';
使用 lodash-es

2024-11-26 13:09 UTC, arvinxx commented on src/config/llm.ts
PROXY_URL 和 MODEL_LIST 已经不需要了，之前的两个PR已经把这块重构掉了

2024-11-27 02:36 UTC, WindWaving commented
> Rebase 下 main，lodash 那个改下，其他没问题了~

已经改好了🙏

2024-11-27 04:21 UTC, arvinxx reviewed
两个 README 的变动撤销下？不应该带在这个 PR 里的

2024-11-27 04:21 UTC, arvinxx commented on src/server/modules/AgentRuntime/index.ts
这一段应该也不需要了，Higress 的配置应该和默认的一样， 走 default 那一段就好

2024-11-27 05:43 UTC, WindWaving commented on src/server/modules/AgentRuntime/index.ts
done🌹

2024-12-06 13:11 UTC, merged

2024-12-06 13:12 UTC, Richardallis411 commented
Release