✨ feat(auth): add WeChat authentication support
lobehub/lobehub pull request #5085
Opened 2024-12-19 09:52 UTC by xiangnanscu

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

Add wechat Oauth support.

#### 📝 补充信息 | Additional Information

2024-12-22 05:47 UTC, arvinxx requested changes

2024-12-22 05:47 UTC, arvinxx commented on src/config/auth.ts
不需要添加了

2024-12-22 05:47 UTC, arvinxx commented on src/config/auth.ts
这里也不需要

2024-12-22 05:47 UTC, arvinxx commented on src/libs/next-auth/sso-providers/wechat.ts
直接用 process.env.xxx

2024-12-23 01:24 UTC, xiangnanscu commented on src/libs/next-auth/sso-providers/wechat.ts
能否说一下是具体哪些process.env变量？

2024-12-23 04:19 UTC, arvinxx commented on src/libs/next-auth/sso-providers/wechat.ts
```
   clientId: process.env.AUTH_WECHAT_ID,
    clientSecret: process.env.AUTH_WECHAT_SECRET,
```
就是不需要前面的 authEnv 了。旧的 authEnv 是为了兼容以前的写法。新的 provider 用新的方案

2024-12-23 04:20 UTC, arvinxx commented
另外最好补充一下 oauth 的配置文档

2024-12-23 05:02 UTC, closed without merging

2024-12-23 05:16 UTC, xiangnanscu commented
> 另外最好补充一下 oauth 的配置文档

OK。有点操作不来，我重新开个PR

2024-12-24 14:00 UTC, xiangnanscu commented on src/config/auth.ts
我看不到具体你说的是哪些行不用参加, 点进去都是一样的diff文件.能否明确一下? 下面四个红框， 哪些红框不用添加？
![image](https://github.com/user-attachments/assets/480190ff-822c-40c9-88f1-9fc45f216567)