🐛 fix: fix HUGGINGFACE endpoint url
lobehub/lobehub pull request #5099
Opened 2024-12-20 09:01 UTC by chai-mi

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change
修复 huggingface endpoint url 设置问题 (#5072)

#### 📝 补充信息 | Additional Information

2024-12-20 09:22 UTC, arvinxx commented on src/libs/agent-runtime/huggingface/index.ts
> +        endpointUrl: instance.baseURL
为什么这样就可以？

2024-12-20 09:58 UTC, chai-mi commented on src/libs/agent-runtime/huggingface/index.ts
> +        endpointUrl: instance.baseURL
`endpointUrl=undefined` 时，SDK 会最终设置为 `${HF_INFERENCE_API_BASE_URL}/models/${model}`，
当设置了 `endpointUrl` 时，SDK 仅仅将其作为最终结果，显然 path 中少了 model 参数

2024-12-20 12:24 UTC, arvinxx requested changes

2024-12-20 12:24 UTC, arvinxx commented on src/libs/agent-runtime/huggingface/index.ts
> +          ? instance.baseURL + '/' + payload.model
使用 urlJoin 方法，不要手动拼接。 urlJoin 会自动处理掉 baseURL 以 `/` 结尾的情况，更加健壮

2024-12-20 12:56 UTC, chai-mi commented on src/libs/agent-runtime/huggingface/index.ts
> +          ? instance.baseURL + '/' + payload.model
已更改

2024-12-21 06:37 UTC, arvinxx approved these changes

2024-12-21 06:38 UTC, merged