✨ feat(auth): add WeChat authentication support
lobehub/lobehub pull request #5195
Opened 2024-12-26 13:18 UTC by xiangnanscu

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

#### 📝 补充信息 | Additional Information

2024-12-26 13:38 UTC, arvinxx reviewed
还需要参考 https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/advanced/auth/next-auth/zitadel.zh-CN.mdx

这里的介绍补充对应的中英文配置文档~

2024-12-26 13:38 UTC, arvinxx commented on src/config/auth.ts
这里不需要添加配置

2024-12-26 14:09 UTC, xiangnanscu commented on src/config/auth.ts
@arvinxx 是整个auth.ts都不需要修改还是部分不需要添加？我看不到具体哪几行

2024-12-27 01:06 UTC, arvinxx commented on src/config/auth.ts
整个都不需要修改

2024-12-27 03:43 UTC, xiangnanscu commented on src/config/auth.ts
@arvinxx OK了

2024-12-27 03:47 UTC, arvinxx requested changes

2024-12-27 03:47 UTC, arvinxx commented on docs/self-hosting/advanced/auth/next-auth/wechat.zh-CN.mdx
> +title: 在 LobeChat 中配置 Wechat 身份验证服务
配置微信身份验证服务

2024-12-27 03:47 UTC, arvinxx commented on docs/self-hosting/advanced/auth/next-auth/wechat.zh-CN.mdx
> +  - Wechat 身份验证
微信身份验证

2024-12-27 03:47 UTC, arvinxx commented on docs/self-hosting/advanced/auth/next-auth/wechat.zh-CN.mdx
> +| `WECHAT_CLIENT_ID`     | 必选 | Wechat 网站应用详情页的 客户端 ID     |
这里应该填写完整的NextAuth 环境变量，英文文档部分也同样如此

2024-12-27 03:57 UTC, xiangnanscu commented on docs/self-hosting/advanced/auth/next-auth/wechat.zh-CN.mdx
> +| `WECHAT_CLIENT_ID`     | 必选 | Wechat 网站应用详情页的 客户端 ID     |
@arvinxx Done

2024-12-28 16:53 UTC, arvinxx approved these changes
LGTM. Thanks for your contribution!

2024-12-28 17:04 UTC, merged