docs: add deploy to Zeabur guide in README
lobehub/lobehub pull request #523
Opened 2023-11-29 07:13 UTC by MichaelYuhe

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [x] 📝 docs

#### 🔀 变更说明 | Description of Change

Add a deploy button for deploying Lobe Chat to Zeabur in `README.md`

#### 📝 补充信息 | Additional Information

2023-11-29 07:28 UTC, arvinxx requested changes
Please add it to the Readme.zh-CN

2023-11-29 07:28 UTC, arvinxx commented on README.md
> +If you want to deploy this service yourself on Vercel, you can follow these steps:
Typo

2023-11-29 07:34 UTC, MichaelYuhe commented on README.md
> +If you want to deploy this service yourself on Vercel, you can follow these steps:
Resolved

2023-11-29 07:36 UTC, MichaelYuhe commented
Thanks for the review, I've also added it to the Readme.zh-CN @arvinxx ,

2023-11-29 07:53 UTC, arvinxx approved these changes
Great work! Thanks~

2023-11-29 07:54 UTC, merged

2023-11-30 08:52 UTC, canisminor1990 commented
@MichaelYuhe plz check the deploy link, Error 500

<img width="1447" alt="image" src="https://github.com/lobehub/lobe-chat/assets/17870709/8cda2d52-26c2-497d-882a-b9cfb7b3b4ec">