✨ feat: `ACCESS_CODE` supports setting multiple
lobehub/lobehub pull request #647
Opened 2023-12-13 13:23 UTC by mushan0x0

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Close #638

#### 📝 补充信息 | Additional Information

2023-12-14 01:38 UTC, arvinxx requested changes

2023-12-14 01:38 UTC, arvinxx commented on README.md
> +| `ACCESS_CODE`             | No       | Add a password to access this service, the password should be 6 digits or letters. The value should be a comma-separated array of strings
文档改错了

2023-12-14 01:38 UTC, arvinxx commented on src/app/api/auth.ts
这块需要补下测试。!accesscode 的实现感觉不一定对。可能会是个空数组？

2023-12-15 01:48 UTC, arvinxx commented on src/app/api/config.test.ts
AccessCode = ''

还有 =  ',,'

=',rdd,dd'

上述几种输入，是否符合预期？

2023-12-15 03:11 UTC, mushan0x0 commented
边界情况加上了 @arvinxx

2023-12-16 11:25 UTC, arvinxx approved these changes

2023-12-16 11:45 UTC, merged