⚡️ feat: Optimize the image upload size for `gpt-4-vision`
lobehub/lobehub pull request #669
Opened 2023-12-15 07:01 UTC by mushan0x0

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

设置图片最大宽度或者高度为 2k，再将图片格式转为 webp

Close #668 #646

#### 📝 补充信息 | Additional Information

压缩之后
<img width="384" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/867d6ffb-619a-4fa3-83b1-14a459d6ea51">

压缩之前
<img width="283" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/f94c8b58-fd76-45d2-b230-3207522569dd">

2023-12-15 07:05 UTC, arvinxx requested changes

2023-12-15 07:05 UTC, arvinxx commented on src/services/file.ts
`uploadFile` 方法定位是个通用方法，除了图片以外，后续 audio 的上传也会复用该方法。因此不建议改这个方法。

考虑新开一个 `updateImage` 方法，在里面实现压缩逻辑，然后再调用 `uploadFile` 方法实现上传。

2023-12-15 07:06 UTC, arvinxx commented
此外，实现思路上可以考虑下，是只存压缩后的缩略图，还是 raw 也存，缩略图也存

2023-12-15 11:53 UTC, canisminor1990 commented
之前自定义头像有个压缩方法 https://github.com/lobehub/lobe-chat/blob/main/src/utils/imageToBase64.ts
感觉可以合一合

2023-12-15 12:05 UTC, mushan0x0 commented
> 之前自定义头像有个压缩方法 https://github.com/lobehub/lobe-chat/blob/main/src/utils/imageToBase64.ts 感觉可以合一合

一开始是用的这个，但是里面有个图片居中逻辑，合并的话不如再抽个文件

2023-12-15 14:45 UTC, mushan0x0 commented on src/services/file.ts
> +    // 跳过图片上传测试
图片压缩这里测试时只能跳过了，应该很难 mock

2023-12-15 14:47 UTC, mushan0x0 commented
> 此外，实现思路上可以考虑下，是只存压缩后的缩略图，还是 raw 也存，缩略图也存

原图就不用存了，占体积也麻烦，本身 webp 跟原图差别也不大

2023-12-15 15:33 UTC, canisminor1990 commented
还有一个思考点，目前压缩图片是通过分辨率判断，是不是通过 blob.size 最大值判断更好

2023-12-15 16:12 UTC, Wxh16144 commented
我也想试着参与你们，在这个 pr 上我补充了一些测试用例。 大佬们看看可以不 😁

2023-12-16 11:54 UTC, arvinxx commented
> 还有一个思考点，目前压缩图片是通过分辨率判断，是不是通过 blob.size 最大值判断更好，理论上应该是在条件允许的可能下，保留更高清的图片的，只是一个想法，实现上可能会触发多次压缩循环，性能应该不太好

@canisminor1990  我感觉不是，应该按照分辨率来。原因是 GPT-4v 模型是按分辨率收钱的：

<img width="900" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/1bd91fc5-b652-492b-9386-70bf54d89258">

目前我的实现中是写死了 `auto` 模式，因此模型会自动识别分别率。比如一张 512x512 的图片，发过去就会是 65 token。

如果是一张分辨率是 12800x25600 的图片，如果限定尺寸，而不限定分辨率，可能是缩小到了 5120x 12800 ，满足了我们的尺寸要求。但发给 4v 之后容易造成更多的 token 浪费。毕竟有可能使用低分辨率就可以描述清楚了。

2023-12-16 12:02 UTC, arvinxx commented on src/services/file.ts
> +    // 跳过图片上传测试
可以使用 LobeChat 测试工程师 来帮你写单测：

 https://chat-preview.lobehub.com/market?agent=lobe-chat-unit-test-dev

现在 LobeChat 中很多单测都是它帮忙写的： https://shareg.pt/xHPM9NJ

2023-12-16 13:40 UTC, canisminor1990 commented
> > 还有一个思考点，目前压缩图片是通过分辨率判断，是不是通过 blob.size 最大值判断更好，理论上应该是在条件允许的可能下，保留更高清的图片的，只是一个想法，实现上可能会触发多次压缩循环，性能应该不太好
> 
> @canisminor1990  我感觉不是，应该按照分辨率来。原因是 GPT-4v 模型是按分辨率收钱的：
> 
> <img width="900" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/1bd91fc5-b652-492b-9386-70bf54d89258">
> 
> refs: https://platform.openai.com/docs/guides/vision/low-or-high-fidelity-image-understanding
> 
> 目前我的实现中是写死了 `auto` 模式，因此模型会自动识别分别率。比如一张 512x512 的图片，发过去就会是 65 token。
> 
> 如果是一张分辨率是 12800x25600 的图片，如果限定尺寸，而不限定分辨率，可能是缩小到了 5120x 12800 ，满足了我们的尺寸要求。但发给 4v 之后容易造成更多的 token 浪费。毕竟有可能使用低分辨率就可以描述清楚了。
> 
> 

这样啊 之前没仔细了解过

2023-12-17 13:49 UTC, arvinxx commented
@mushan0x0 merge 下 main ？ 有冲突

2023-12-17 14:23 UTC, mushan0x0 commented
好的，晚点处理一下

2023-12-18 12:51 UTC, merged