✨ feat: Add image download functionality to DallE render component
lobehub/lobehub pull request #778
Opened 2023-12-23 10:03 UTC by Justin3go

#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

在DallE中的图片预览中增加下载功能，页面预览如下：

![image](https://github.com/lobehub/lobe-chat/assets/63507251/453e49d4-69e1-4a27-8708-052d6555a03d)

#### 📝 补充信息 | Additional Information

当前并未实现下载功能，因为lobe-ui中的preview组件的当前实现不能获取当前图片数组的下标，所以需要等lobe-ui发版之后，这里再更新一下组件库版号应该就可以了

```tsx
  onVisibleChange: (visible: boolean, _prevVisible: boolean, current: number) => {
    if (visible) {
      setCurrent(current);
    }
  },
```
` _prevVisible: boolean, current: numbe`这两个参数传不进去

[lobe-ui的PR链接](https://github.com/lobehub/lobe-ui/pull/98)

2023-12-23 10:07 UTC, arvinxx commented
> 这里再更新一下组件库版号应该就可以了

lobe-ui 的 form 组件重构了一版，样式有点问题。得等 @canisminor1990 修好再升上去了。

2023-12-23 10:10 UTC, arvinxx requested changes

2023-12-23 10:10 UTC, arvinxx commented on src/tools/dalle/Render/index.tsx
> +import { DownloadOutlined } from '@ant-design/icons';
图标使用 ：https://lucide.dev/icons/download

2023-12-23 10:10 UTC, arvinxx commented on src/tools/dalle/Render/index.tsx
> +            <Button
按钮使用 lobe-ui 的 ActionIcon ：https://ui.lobehub.com/components/action-icon 

看下这块扩展的实现 cc @canisminor1990

2023-12-23 10:13 UTC, Justin3go commented
> > 这里再更新一下组件库版号应该就可以了
> 
> lobe-ui 的 form 组件重构了一版，样式有点问题。得等 @canisminor1990 修好再升上去了。

那边也提了个PR，增加了传入参数：https://github.com/lobehub/lobe-ui/pull/98

2023-12-24 11:40 UTC, arvinxx requested changes

2023-12-24 11:40 UTC, arvinxx commented on src/tools/dalle/Render/index.tsx
> +    const currentImage = content[current]?.previewUrl;
这里不应该使用这个字段，`previewUrl` 会在1小时后过期的， 需要使用 imageId 来获取对应的blob url。

2023-12-24 11:59 UTC, canisminor1990 commented
> > 这里再更新一下组件库版号应该就可以了
> 
> lobe-ui 的 form 组件重构了一版，样式有点问题。得等 @canisminor1990 修好再升上去了。

我修好了

2023-12-25 02:44 UTC, Justin3go commented
> > > 这里再更新一下组件库版号应该就可以了
> > 
> > 
> > lobe-ui 的 form 组件重构了一版，样式有点问题。得等 @canisminor1990 修好再升上去了。
> 
> 我修好了

麻烦再看一下呀，好像[最近一次发版](https://github.com/lobehub/lobe-ui/commits/master/)并没有带上我的提交样：

![image](https://github.com/lobehub/lobe-chat/assets/63507251/289882d4-edc9-4615-a432-f3bedf2a238e)

2023-12-25 02:45 UTC, Justin3go commented on src/tools/dalle/Render/index.tsx
> +    const currentImage = content[current]?.previewUrl;
已经改了，辛苦再看一看，这里由于获取blob url也是异步操作，所以增加了状态变量以及使用了useEffect，不知道是否会有一些问题

2023-12-25 06:56 UTC, Justin3go commented
刚才将lobe-ui的版号更新到最新的1.124.0了，下载功能已经实现，目前自测是没有问题的，效果演示如下：

![PixPin_2023-12-25_14-54-18](https://github.com/lobehub/lobe-chat/assets/63507251/aaeb1f2e-d089-4c20-b88c-6a1ced6f8201)

2023-12-26 14:57 UTC, arvinxx requested changes

2023-12-26 14:57 UTC, arvinxx commented on package.json
> +    "@lobehub/ui": "~1.124.0",
同步一下最新分支

2023-12-26 14:57 UTC, arvinxx commented on src/tools/dalle/Render/index.tsx
> +  useEffect(() => {
这个实现逻辑不太好，不应用 `useEffect` 监听事件来做。应该要用主动获取 data 的方式拿到 blob 对象再下载。

现在这种实现感觉过于弯弯绕绕了。你直接调用 `fileService.getFile` 取到 url 不是更简单么？

2023-12-27 00:53 UTC, Justin3go commented on src/tools/dalle/Render/index.tsx
> +  useEffect(() => {
OKOK，感谢CR🥳🥳🥳

2023-12-27 15:46 UTC, arvinxx approved these changes

2023-12-27 15:47 UTC, merged