🔨 chore: Add Vietnamese files and add the vi-VN option in the General Settings
lobehub/lobehub pull request #860
Opened 2023-12-29 03:18 UTC by CongLeSolutionX

#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [x] 🔨 chore: Add Vietnamese files and add the vi-VN option in the General Settings
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change
- Inside `locales` folder, I added a folder `vi-VN`. Inside that folder, I added the same json files used to support languges: 
   - chat.json
   - common.json
   - empty.json
   - error.json
   - market.json
   - migration.json
   - plugin.json
   - setting.json
   - tool.json
   - welcom.json
 - Inside each of those json file, I translated all the pairs of  value to support Vietnamese.
 - Inside file `src/locales/resources.ts`, I added code to support Vietnames, loading data from folder vi-VN.

#### 📝 Demo: 
![demo-better](https://github.com/lobehub/lobe-chat/assets/31250006/ab57c10e-1cd2-4c5b-8c76-04cf480db0f6)

2023-12-29 09:28 UTC, arvinxx requested changes
please add the `vi-VN` into the `i18nrc.js` and run `npm run i18n`.

https://github.com/lobehub/lobe-chat/blob/main/.i18nrc.js#L7

we won't update the i18n manually. So we use `lobe-i18n` to auto translate locale.

You can check  simmiliar pr like: https://github.com/lobehub/lobe-chat/pull/759

2023-12-29 09:28 UTC, arvinxx commented on src/app/layout.tsx
> +import { SpeedInsights } from '@vercel/speed-insights/next';
please don't introduce it

2023-12-29 09:28 UTC, arvinxx commented on package.json
please revert this change

2024-01-03 06:48 UTC, CongLeSolutionX commented on src/app/layout.tsx
> +import { SpeedInsights } from '@vercel/speed-insights/next';
ok, let me remove it

2024-01-03 06:48 UTC, CongLeSolutionX commented
> please add the `vi-VN` into the `i18nrc.js` and run `npm run i18n`.
> 
> https://github.com/lobehub/lobe-chat/blob/main/.i18nrc.js#L7
> 
> we won't update the i18n manually. So we use `lobe-i18n` to auto translate locale.
> 
> You can check simmiliar pr like: #759

Thanks for your feedback, let me update this PR

2024-01-03 07:50 UTC, CongLeSolutionX commented on package.json
ok

2024-01-03 07:54 UTC, CongLeSolutionX commented
> please add the `vi-VN` into the `i18nrc.js` and run `npm run i18n`.
> 
> https://github.com/lobehub/lobe-chat/blob/main/.i18nrc.js#L7
> 
> we won't update the i18n manually. So we use `lobe-i18n` to auto translate locale.
> 
> You can check simmiliar pr like: #759

Hi @arvinxx,
I follow your instructions to use `.i18nrc.js` to translate all files in the vi-VN folder.
`.i18nrc.js` also picks up the missing string "downloading" as well, so I add those changes to this PR.

2024-01-03 08:53 UTC, arvinxx approved these changes
Thanks for your great job!

2024-01-03 09:00 UTC, merged